/**
 * BIM Document Types
 * Ported 1:1 from extension/js/config.js — CONFIG.DOCUMENT_TYPES
 *
 * Structure: grouped object keyed by category slug.
 * Each group has a label (with emoji) and an items array.
 * Some items (contracts, doe, bim-coord groups) carry an optional tooltip.
 */

import type { DocumentType, DocumentTypeGroup, Discipline } from '../types';

export const DOCUMENT_TYPES: Record<string, DocumentTypeGroup> = {
  reports: {
    label: '📋 Rapports & PV',
    items: [
      { code: 'RAP', name: 'Rapport' },
      { code: 'PV', name: 'Procès-verbal' },
      { code: 'RAP-MPR', name: 'Rapport mise en pression' },
      { code: 'RAP-ESS', name: 'Rapport essai' },
      { code: 'RAP-CTR', name: 'Rapport contrôle' },
      { code: 'RAP-REC', name: 'Rapport réception' },
      { code: 'RAP-INS', name: 'Rapport inspection' },
      { code: 'RAP-AUD', name: 'Rapport audit' },
      { code: 'RAP-CHN', name: 'Rapport chantier' },
      { code: 'RAP-AVN', name: 'Rapport avancement' },
      { code: 'RAP-QUA', name: 'Rapport qualité' },
      { code: 'RAP-SEC', name: 'Rapport sécurité' },
      { code: 'RAP-ENV', name: 'Rapport environnement' },
      { code: 'RAP-INC', name: 'Rapport incident' },
      { code: 'RAP-NCF', name: 'Rapport non-conformité' },
      { code: 'RAP-FIN', name: 'Rapport final' },
      { code: 'RAP-INT', name: 'Rapport intermédiaire' },
      { code: 'RAP-TEC', name: 'Rapport technique' },
      { code: 'RAP-EXP', name: 'Rapport expertise' },
      { code: 'RAP-DIA', name: 'Rapport diagnostic' },
      { code: 'RAP-THE', name: 'Rapport thermique' },
      { code: 'RAP-ACO', name: 'Rapport acoustique' },
      { code: 'RAP-STR', name: 'Rapport structure' },
      { code: 'RAP-GEO', name: 'Rapport géotechnique' },
      { code: 'RAP-HYD', name: 'Rapport hydraulique' },
      { code: 'RAP-ELE', name: 'Rapport électrique' },
      { code: 'RAP-CVC', name: 'Rapport CVC' },
      { code: 'RAP-PLB', name: 'Rapport plomberie' },
      { code: 'RAP-SPK', name: 'Rapport sprinkler' },
      { code: 'RAP-SSI', name: 'Rapport SSI' },
      { code: 'RAP-ASC', name: 'Rapport ascenseurs' },
      { code: 'RAP-VER', name: 'Rapport vérification' },
      { code: 'RAP-MES', name: 'Rapport mesures' },
      { code: 'RAP-ANL', name: 'Rapport analyse' },
      { code: 'RAP-SYN', name: 'Rapport synthèse' },
      { code: 'RAP-PRESSION', name: 'Rapport pression' },
      { code: 'RAP-FORAGE', name: 'Rapport forage' },
      { code: 'RAP-SONDAGE', name: 'Rapport sondage' },
      { code: 'PV-REU', name: 'PV réunion' },
      { code: 'PV-CHA', name: 'PV chantier' },
      { code: 'PV-REC', name: 'PV réception' },
      { code: 'PV-LIV', name: 'PV livraison' },
      { code: 'PV-OPR', name: 'PV OPR' },
      { code: 'PV-LEV', name: 'PV levée réserves' },
      { code: 'PV-ESS', name: 'PV essais' },
      { code: 'PV-MES', name: 'PV mesures' },
      { code: 'PV-CTR', name: 'PV contrôle' },
      { code: 'PV-COO', name: 'PV coordination' },
      { code: 'CR', name: 'Compte-rendu' },
      { code: 'CR-REU', name: 'CR réunion' },
      { code: 'CR-CHA', name: 'CR chantier' },
    ],
  },
  plans: {
    label: '📐 Plans & Modèles BIM',
    items: [
      { code: 'PLA', name: 'Plan 2D' },
      { code: 'IFC', name: 'Modèle IFC' },
      { code: 'COU', name: 'Coupe' },
      { code: 'PLA-ARC', name: 'Plan architecture' },
      { code: 'PLA-STR', name: 'Plan structure' },
      { code: 'PLA-CVC', name: 'Plan CVC' },
      { code: 'PLA-ELE', name: 'Plan électricité' },
      { code: 'PLA-PLB', name: 'Plan plomberie' },
      { code: 'PLA-EXE', name: 'Plan exécution' },
      { code: 'PLA-DET', name: 'Plan détail' },
      { code: 'SCH', name: 'Schéma' },
      { code: 'FAC', name: 'Façade' },
      { code: 'ELV', name: 'Élévation' },
      { code: 'DET', name: 'Détail' },
    ],
  },
  technical: {
    label: '📄 Documentation Technique',
    items: [
      { code: 'DOCTEC', name: 'Documentation technique' },
      { code: 'CER', name: 'Certificat' },
      { code: 'NOT-TEC', name: 'Notice technique' },
      { code: 'NOT-FAB', name: 'Notice fabricant' },
      { code: 'FIC-TEC', name: 'Fiche technique' },
      { code: 'SPE', name: 'Spécification' },
      { code: 'MAN', name: 'Manuel' },
      { code: 'MOD-EMP', name: 'Mode emploi' },
      { code: 'MAI', name: 'Document maintenance' },
    ],
  },
  tests: {
    label: '🔬 Tests & Essais',
    items: [
      { code: 'TST', name: 'Test' },
      { code: 'ESS', name: 'Essai' },
      { code: 'TST-PRE', name: 'Test pression' },
      { code: 'TST-ETA', name: 'Test étanchéité' },
      { code: 'TST-FUM', name: 'Test fumée' },
      { code: 'TST-DES', name: 'Test désenfumage' },
      { code: 'TST-EAU', name: 'Test eau' },
      { code: 'TST-AIR', name: 'Test air' },
      { code: 'TST-GAZ', name: 'Test gaz' },
      { code: 'TST-ELE', name: 'Test électrique' },
      { code: 'TST-ISO', name: 'Test isolation' },
      { code: 'TST-TER', name: 'Test terre' },
      { code: 'TST-CON', name: 'Test continuité' },
      { code: 'TST-DIF', name: 'Test différentiel' },
      { code: 'TST-THE', name: 'Test thermique' },
      { code: 'TST-ACO', name: 'Test acoustique' },
      { code: 'TST-VIB', name: 'Test vibration' },
      { code: 'TST-DEB', name: 'Test débit' },
      { code: 'TST-VIT', name: 'Test vitesse' },
      { code: 'TST-TMP', name: 'Test température' },
      { code: 'TST-HUM', name: 'Test humidité' },
      { code: 'TST-LUM', name: 'Test luminosité' },
      { code: 'TST-QAI', name: 'Test qualité air' },
      { code: 'TST-FEU', name: 'Test feu' },
      { code: 'TST-CHG', name: 'Test charge' },
      { code: 'TST-PER', name: 'Test performance' },
      { code: 'TST-FON', name: 'Test fonctionnel' },
      { code: 'TST-REG', name: 'Test régulation' },
      { code: 'TST-AUT', name: 'Test automatisme' },
      { code: 'TST-COM', name: 'Test communication' },
      { code: 'TST-RES', name: 'Test réseau' },
      { code: 'TST-BAL', name: 'Test balancement' },
      { code: 'TST-EQU', name: 'Test équilibrage' },
      { code: 'TST-CIR', name: 'Test circulation' },
      { code: 'TST-VAN', name: 'Test vanne' },
      { code: 'TST-PMP', name: 'Test pompe' },
      { code: 'TST-VNT', name: 'Test ventilateur' },
      { code: 'TST-CTA', name: 'Test CTA' },
      { code: 'TST-CHD', name: 'Test chaudière' },
      { code: 'TST-PAC', name: 'Test PAC' },
      { code: 'TST-GRP', name: 'Test groupe froid' },
      { code: 'TST-SPK', name: 'Test sprinkler' },
      { code: 'TST-RIA', name: 'Test RIA' },
      { code: 'TST-EXT', name: 'Test extincteurs' },
      { code: 'TST-SSI', name: 'Test SSI' },
      { code: 'TST-DET', name: 'Test détection' },
      { code: 'TST-ALR', name: 'Test alarme' },
      { code: 'TST-EVA', name: 'Test évacuation' },
      { code: 'TST-GTC', name: 'Test GTC' },
      { code: 'TST-ASC', name: 'Test ascenseur' },
      { code: 'TST-ESC', name: 'Test escalier méca' },
      { code: 'TST-POR', name: 'Test portes' },
      { code: 'TST-CTR', name: 'Test contrôle accès' },
      { code: 'TST-VID', name: 'Test vidéo' },
      { code: 'TST-INT', name: 'Test intrusion' },
      { code: 'MES', name: 'Mesure' },
      { code: 'MES-DEB', name: 'Mesure débit' },
      { code: 'MES-PRE', name: 'Mesure pression' },
      { code: 'MES-TMP', name: 'Mesure température' },
      { code: 'MES-HUM', name: 'Mesure humidité' },
      { code: 'MES-ACO', name: 'Mesure acoustique' },
      { code: 'MES-LUM', name: 'Mesure luminosité' },
      { code: 'MES-ELE', name: 'Mesure électrique' },
      { code: 'MES-THE', name: 'Mesure thermique' },
      { code: 'PRO-TST', name: 'Protocole test' },
      { code: 'PRO-ESS', name: 'Protocole essai' },
      { code: 'PRO-MES', name: 'Protocole mesure' },
      { code: 'PRO-REC', name: 'Protocole réception' },
    ],
  },
  quotes: {
    label: '📊 Devis & Métrés',
    items: [
      { code: 'DEV', name: 'Devis' },
      { code: 'MET', name: 'Métré' },
      { code: 'OFF', name: 'Offre' },
      { code: 'BON-CMD', name: 'Bon commande' },
      { code: 'FAC', name: 'Facture' },
    ],
  },
  certifications: {
    label: '📑 Certifications & Conformité',
    items: [
      { code: 'CER', name: 'Certificat' },
      { code: 'ATT', name: 'Attestation' },
      { code: 'DEC-CON', name: 'Déclaration conformité' },
      { code: 'LAB', name: 'Label' },
      { code: 'HOM', name: 'Homologation' },
    ],
  },
  lists: {
    label: '📋 Listes & Inventaires',
    items: [
      { code: 'LIS', name: 'Liste' },
      { code: 'INV', name: 'Inventaire' },
      { code: 'NOM', name: 'Nomenclature' },
      { code: 'BOR', name: 'Bordereau' },
    ],
  },
  media: {
    label: '📸 Photos & Médias',
    items: [
      { code: 'PHO', name: 'Photo' },
      { code: 'PHO-CHA', name: 'Photo chantier' },
      { code: 'VID', name: 'Vidéo' },
      { code: 'SCA', name: 'Scan' },
    ],
  },
  admin: {
    label: '📝 Administratif',
    items: [
      { code: 'CTR', name: 'Contrat' },
      { code: 'CTR-MAI', name: 'Contrat maintenance' },
      { code: 'CNV', name: 'Convention' },
      { code: 'CDC', name: 'Cahier charges' },
      { code: 'ANX', name: 'Annexe' },
      { code: 'COU', name: 'Courrier' },
      { code: 'NOT', name: 'Note' },
    ],
  },
  bim: {
    label: '🏗️ BIM & Modélisation',
    items: [
      { code: 'MOD-BIM', name: 'Modèle BIM' },
      { code: 'MAQ-NUM', name: 'Maquette numérique' },
      { code: 'BCF', name: 'BCF' },
      { code: 'RVT', name: 'Fichier Revit' },
      { code: 'NWD', name: 'Navisworks' },
      { code: 'COB', name: 'Export COBie' },
    ],
  },
  contracts: {
    label: '📝 Marchés & Contrats',
    items: [
      { code: 'CCTP', name: 'Cahier des Clauses Techniques Particulières', tooltip: 'Description technique détaillée des travaux' },
      { code: 'DPGF', name: 'Décomposition du Prix Global Forfaitaire', tooltip: 'Détail des prix par poste de travaux' },
      { code: 'DQE', name: 'Détail Quantitatif Estimatif', tooltip: 'Quantités et estimations prévisionnelles' },
      { code: 'BPU', name: 'Bordereau des Prix Unitaires', tooltip: 'Prix unitaires contractuels applicables' },
      { code: 'OS', name: 'Ordre de Service', tooltip: 'Instructions contractuelles de démarrage/arrêt' },
      { code: 'AVN', name: 'Avenant', tooltip: 'Modification du contrat initial' },
      { code: 'SIT', name: 'Situation de Travaux', tooltip: 'État d\'avancement pour facturation' },
      { code: 'DGD', name: 'Décompte Général Définitif', tooltip: 'Solde de tout compte final' },
      { code: 'ACT', name: 'Acte d\'Engagement', tooltip: 'Document contractuel d\'engagement' },
      { code: 'RC', name: 'Règlement de Consultation', tooltip: 'Règles de la consultation' },
    ],
  },
  doe: {
    label: '📚 DOE & Exploitation',
    items: [
      { code: 'DOE', name: 'Dossier des Ouvrages Exécutés', tooltip: 'Documentation finale de construction' },
      { code: 'DIUO', name: 'Dossier d\'Intervention Ultérieure', tooltip: 'Sécurité pour interventions futures' },
      { code: 'AOR', name: 'Attestation d\'Achèvement', tooltip: 'Document de fin de travaux' },
      { code: 'PV-REC', name: 'PV de Réception', tooltip: 'Procès-verbal de réception des travaux' },
      { code: 'GAR', name: 'Garantie', tooltip: 'Documents de garantie contractuelle' },
      { code: 'MAI-DOC', name: 'Documentation Maintenance', tooltip: 'Carnet d\'entretien et maintenance' },
      { code: 'EXP-DOC', name: 'Guide d\'Exploitation', tooltip: 'Manuel d\'exploitation du bâtiment' },
      { code: 'REG', name: 'Registre de Sécurité', tooltip: 'Registre obligatoire de sécurité' },
      { code: 'CAR-ENT', name: 'Carnet d\'Entretien', tooltip: 'Suivi des opérations d\'entretien' },
    ],
  },
  'bim-coord': {
    label: '🔄 Coordination BIM',
    items: [
      { code: 'BIM-CONV', name: 'Convention BIM', tooltip: 'Règles de collaboration et échanges BIM' },
      { code: 'BIM-EXE', name: 'Plan d\'Exécution BIM (BEP)', tooltip: 'BIM Execution Plan du projet' },
      { code: 'BCF-RPT', name: 'Rapport BCF', tooltip: 'BIM Collaboration Format - annotations' },
      { code: 'CLR', name: 'Clash Report', tooltip: 'Rapport de détection de conflits' },
      { code: 'LOD', name: 'Spécification LOD', tooltip: 'Level of Development requis' },
      { code: 'SYN-BIM', name: 'Maquette Synthèse', tooltip: 'Maquette de coordination tous corps d\'état' },
      { code: 'FED', name: 'Modèle Fédéré', tooltip: 'Assemblage des maquettes métier' },
      { code: 'CHK', name: 'Checklist BIM', tooltip: 'Liste de contrôle qualité maquette' },
      { code: 'QTO', name: 'Quantités BIM (QTO)', tooltip: 'Quantity Take-Off depuis maquette' },
    ],
  },
  phases: {
    label: '📅 Phases Projet',
    items: [
      { code: 'ESQ', name: 'Esquisse', tooltip: 'Phase esquisse - intentions générales' },
      { code: 'APS', name: 'Avant-Projet Sommaire', tooltip: 'Définition du programme' },
      { code: 'APD', name: 'Avant-Projet Définitif', tooltip: 'Conception détaillée' },
      { code: 'PRO', name: 'Projet', tooltip: 'Phase projet - études approfondies' },
      { code: 'DCE', name: 'DCE', tooltip: 'Dossier de Consultation des Entreprises' },
      { code: 'EXE', name: 'Exécution', tooltip: 'Plans d\'exécution chantier' },
      { code: 'REC-PHA', name: 'Réception', tooltip: 'Phase de réception des travaux' },
      { code: 'OPR', name: 'OPR', tooltip: 'Opérations Préalables à la Réception' },
      { code: 'PAR', name: 'Parfait Achèvement', tooltip: 'Année de parfait achèvement' },
      { code: 'GPA', name: 'GPA', tooltip: 'Garantie de Parfait Achèvement' },
    ],
  },
  other: {
    label: '🔧 Autres',
    items: [
      { code: 'AUT', name: 'Autre' },
      { code: 'DIV', name: 'Divers' },
    ],
  },
};

/** Flatten all document types from all groups into a single array */
export function getAllDocumentTypes(): DocumentType[] {
  return Object.values(DOCUMENT_TYPES).flatMap(group => group.items);
}

/** Find a document type by code across all groups */
export function getDocumentType(code: string): DocumentType | undefined {
  for (const group of Object.values(DOCUMENT_TYPES)) {
    const found = group.items.find(item => item.code === code);
    if (found) return found;
  }
  return undefined;
}

/**
 * DISCIPLINES — from CONFIG.DISCIPLINES
 * Lightweight code/name pairs; note some codes overlap with WORK_LOTS
 * (this is intentional in the source — they serve different UI contexts).
 */
export const DISCIPLINES: Discipline[] = [
  { code: 'ARC', name: 'Architecture' },
  { code: 'STR', name: 'Structure' },
  { code: 'CVC', name: 'CVC / HVAC' },
  { code: 'ELE', name: 'Électricité' },
  { code: 'PLB', name: 'Plomberie' },
  { code: 'SPK', name: 'Sprinkler' },
  { code: 'SEC', name: 'Sécurité incendie' },
  { code: 'FAC', name: 'Façade' },
  { code: 'INT', name: 'Intérieurs' },
  { code: 'PAY', name: 'Paysage' },
  { code: 'VRD', name: 'VRD' },
  { code: 'GTC', name: 'GTC/GTB' },
  { code: 'SSI', name: 'SSI' },
  { code: 'ASC', name: 'Ascenseurs' },
  { code: 'CUI', name: 'Cuisine' },
  { code: 'INF', name: 'Informatique' },
  { code: 'AUD', name: 'Audiovisuel' },
  { code: 'MUL', name: 'Multi-disciplines' },
  { code: 'GEN', name: 'Général' },
];
