import type {
  DocumentTypeDefinition,
  EntityTypeDefinition,
  IndustryProfile,
  NamingField,
  NamingTemplate,
} from './types';

const doc = (
  id: string,
  label: string,
  abbreviation: string,
  category?: string,
  aliases: string[] = [],
): DocumentTypeDefinition => ({ id, label, abbreviation, category, aliases });

const entity = (id: string, label: string, pluralLabel: string, examples: string[] = []): EntityTypeDefinition => ({
  id,
  label,
  pluralLabel,
  examples,
});

const field = (
  id: string,
  label: string,
  kind: NamingField['kind'],
  placeholder?: string,
  required = false,
  examples: string[] = [],
): NamingField => ({ id, label, kind, placeholder, required, examples });

const template = (
  id: string,
  label: string,
  description: string,
  fields: string[],
  example: string,
  defaultSeparator: '_' | '-' | '.' = '_',
  disclaimer = 'Modèle de départ à adapter à votre convention interne.',
): NamingTemplate => ({ id, label, description, fields, example, defaultSeparator, disclaimer });

const genericStatuses = [
  doc('draft', 'Brouillon', 'BROUILLON'),
  doc('valid', 'Valide', 'VALIDE', undefined, ['valide']),
  doc('final', 'Final', 'FINAL'),
  doc('archived', 'Archive', 'ARCHIVE', undefined, ['archive']),
];

export const INDUSTRY_PROFILES: IndustryProfile[] = [
  {
    id: 'bim-construction',
    label: 'BIM / Construction',
    shortLabel: 'BIM',
    description: 'Conventions de nommage pour livrables BIM, plans, maquettes, rapports techniques et dépôts CDE.',
    recommendedFor: ['BIM managers', 'coordinateurs BIM', 'architectes', 'bureaux d’études', 'entreprises générales'],
    entityImportLabel: 'Importer des entreprises / émetteurs',
    defaultSeparator: '_',
    entityTypes: [
      entity('company', 'Entreprise', 'Entreprises'),
      entity('originator', 'Émetteur', 'Émetteurs'),
      entity('engineering-office', 'Bureau d’études', 'Bureaux d’études'),
      entity('architect', 'Architecte', 'Architectes'),
      entity('client', 'Client', 'Clients'),
      entity('agent', 'Mandataire', 'Mandataires'),
      entity('lot', 'Lot', 'Lots'),
      entity('discipline', 'Discipline', 'Disciplines'),
    ],
    fields: [
      field('project', 'Projet', 'free-text', 'PROJET', true),
      field('building', 'Bâtiment', 'free-text', 'BAT'),
      field('originator', 'Émetteur', 'entity', 'BET'),
      field('company', 'Entreprise', 'entity', 'ENT'),
      field('zone', 'Zone', 'free-text', 'ZN01'),
      field('level', 'Niveau', 'free-text', 'NIV01'),
      field('discipline', 'Discipline', 'select', 'ARC'),
      field('workLot', 'Lot', 'select', 'CVC'),
      field('docType', 'Type de document', 'document-type', 'PLAN', true),
      field('sequence', 'Numéro', 'number', '001'),
      field('revision', 'Révision', 'revision', 'REV01'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('filename', 'Nom original nettoyé', 'free-text'),
    ],
    documentTypes: [
      doc('plan', 'Plan', 'PLAN', 'Plan', ['plans']),
      doc('section', 'Coupe', 'COUPE', 'Plan', ['coupes']),
      doc('facade', 'Façade', 'FACADE', 'Plan', ['facade', 'facades']),
      doc('detail', 'Détail', 'DETAIL', 'Plan'),
      doc('digital-model', 'Maquette numérique', 'MN', 'Maquette', ['maquette', 'maquette bim', 'model']),
      doc('ifc', 'Fichier IFC', 'IFC', 'Maquette'),
      doc('dwg', 'Fichier DWG', 'DWG', 'CAO'),
      doc('bim-report', 'Rapport BIM', 'RAP_BIM', 'Coordination'),
      doc('synthesis-report', 'Rapport de synthèse', 'RAP_SYN', 'Coordination'),
      doc('calculation-note', 'Note de calcul', 'NDC', 'Technique', ['notes de calcul']),
      doc('technical-sheet', 'Fiche technique', 'FT', 'Technique', ['fiche produit']),
      doc('transmittal', 'Bordereau', 'BORD', 'Diffusion', ['bordereau de diffusion']),
      doc('schedule', 'Planning', 'PLANNING', 'Projet'),
      doc('minutes', 'Compte rendu', 'CR', 'Projet', ['compte-rendu']),
      doc('site-minutes', 'Compte rendu chantier', 'CR_CHANTIER', 'Projet'),
      doc('pv', 'Procès-verbal', 'PV', 'Projet', ['proces verbal', 'proces-verbal']),
      doc('notice', 'Notice', 'NOTICE', 'Technique'),
      doc('as-built', 'Dossier des ouvrages exécutés', 'DOE', 'Livraison'),
      doc('visa', 'Visa', 'VISA', 'Validation'),
      doc('observation', 'Fiche observation', 'FO', 'Contrôle'),
      doc('control-report', 'Rapport de contrôle', 'RAP_CTRL', 'Contrôle'),
      doc('technical-document', 'Document technique', 'DOCTECH', 'Technique', ['documents techniques', 'doc technique', 'documentation technique']),
    ],
    statuses: [
      doc('s0', 'Travail en cours', 'S0'),
      doc('s1', 'Partagé', 'S1'),
      doc('a1', 'Approuvé', 'A1'),
      doc('rev', 'Révision', 'REV'),
      ...genericStatuses,
    ],
    templates: [
      template('cde-delivery', 'Livraison CDE', 'Structure simple pour lots de fichiers avant dépôt.', ['project', 'building', 'workLot', 'docType', 'company', 'sequence'], 'PROJET_BAT_CVC_PLAN_ENT_001'),
      template('iso19650', 'ISO 19650 inspiré', 'Structure inspirée de pratiques ISO 19650.', ['project', 'originator', 'discipline', 'zone', 'docType', 'sequence', 'revision'], 'PROJET-ORG-ARC-ZN01-PLAN-001-P01', '-', 'Modèle inspiré de pratiques de nommage BIM. Ne constitue pas une certification.'),
      template('swiss-bim', 'SIA inspiré', 'Structure inspirée de conventions BIM suisses.', ['project', 'building', 'discipline', 'docType', 'sequence', 'revision'], 'PROJET_BAT_ARC_PLAN_001_A', '_', 'Modèle inspiré de pratiques de nommage BIM. Ne constitue pas une certification.'),
      template('french-bim', 'BIM France inspiré', 'Structure projet, phase, discipline et type.', ['project', 'building', 'discipline', 'docType', 'level', 'sequence'], 'PROJET-BAT-ARC-PLAN-NIV01-001', '-', 'Modèle inspiré de pratiques de nommage BIM. Ne constitue pas une certification.'),
      template('custom', 'Convention projet personnalisée', 'Base libre à adapter au protocole projet.', ['project', 'docType', 'sequence', 'revision'], 'PROJET_PLAN_001_REV01'),
    ],
    disclaimers: ['Les modèles BIM fournis sont des points de départ, pas des certifications de conformité.'],
  },
  {
    id: 'finance',
    label: 'Finance',
    shortLabel: 'Finance',
    description: 'Classement de factures, justificatifs, rapports financiers, budgets, clôtures et pièces comptables.',
    recommendedFor: ['comptables', 'contrôleurs de gestion', 'DAF', 'cabinets d’audit'],
    entityImportLabel: 'Importer des clients / fournisseurs / entités',
    defaultSeparator: '_',
    entityTypes: [
      entity('client', 'Client', 'Clients'),
      entity('supplier', 'Fournisseur', 'Fournisseurs'),
      entity('entity', 'Entité', 'Entités'),
      entity('company', 'Société', 'Sociétés'),
      entity('cost-center', 'Centre de coût', 'Centres de coût'),
      entity('fiscal-year', 'Exercice', 'Exercices'),
      entity('finance-service', 'Service financier', 'Services financiers'),
    ],
    fields: [
      field('entity', 'Client, fournisseur ou entité', 'entity', 'CLIENT', true),
      field('year', 'Année', 'number', '2026'),
      field('month', 'Mois', 'number', '05'),
      field('docType', 'Type de document', 'document-type', 'FAC', true),
      field('reference', 'Référence', 'free-text', 'REF'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoyé', 'free-text'),
    ],
    documentTypes: [
      doc('invoice', 'Facture', 'FAC', 'Comptabilité', ['invoice']),
      doc('credit-note', 'Avoir', 'AVOIR', 'Comptabilité', ['note de credit']),
      doc('quote', 'Devis', 'DEVIS', 'Vente'),
      doc('purchase-order', 'Bon de commande', 'BC', 'Achat'),
      doc('bank-statement', 'Relevé bancaire', 'RELBQ', 'Banque', ['releve bancaire']),
      doc('supporting-document', 'Justificatif', 'JUSTIF', 'Comptabilité', ['piece justificative', 'piece justificative']),
      doc('financial-report', 'Rapport financier', 'RAPFIN', 'Reporting', ['reporting financier']),
      doc('budget', 'Budget', 'BUDGET', 'Reporting', ['previsionnel', 'budget previsionnel']),
      doc('closing', 'Clôture', 'CLOTURE', 'Comptabilité', ['closing']),
      doc('audit', 'Audit', 'AUDIT', 'Audit', ['rapport audit']),
      doc('expense-report', 'Note de frais', 'NDF', 'Frais', ['frais']),
      doc('contract', 'Contrat', 'CTR', 'Contrat', ['contract']),
      doc('schedule', 'Échéancier', 'ECH', 'Suivi'),
      doc('tracking-table', 'Tableau de suivi', 'SUIVI', 'Suivi'),
      doc('trial-balance', 'Balance', 'BALANCE', 'Comptabilité'),
      doc('ledger', 'Grand livre', 'GL', 'Comptabilité'),
      doc('accounting-export', 'Export comptable', 'EXP_COMPTA', 'Comptabilité'),
      doc('declaration', 'Déclaration', 'DECL', 'Fiscal'),
      doc('bank-reconciliation', 'Rapprochement bancaire', 'RAPP_BQ', 'Banque'),
    ],
    statuses: [...genericStatuses, doc('paid', 'Payé', 'PAYE'), doc('pending', 'En attente', 'ATTENTE')],
    templates: [
      template('finance-monthly', 'Classement mensuel', 'Classement par entité, période, type et référence.', ['entity', 'year', 'month', 'docType', 'reference', 'status'], 'ENTITE_2026_05_FAC_REF_VALIDE'),
      template('finance-client', 'Dossier client', 'Structure orientée client et exercice.', ['entity', 'year', 'docType', 'reference', 'version'], 'CLIENT_2026_RAPFIN_REF_V01'),
      template('finance-audit', 'Audit financier', 'Structure pour pièces et livrables d’audit.', ['entity', 'year', 'docType', 'reference', 'status', 'version'], 'CLIENT_2026_AUDIT_REF_FINAL_V01'),
      template('finance-pieces', 'Pièces comptables', 'Structure simple pour factures et justificatifs.', ['entity', 'year', 'month', 'docType', 'reference'], 'FOURNISSEUR_2026_05_FAC_REF'),
      template('custom', 'Convention personnalisée', 'Base libre à adapter.', ['entity', 'docType', 'reference', 'version'], 'ENTITE_TYPE_REF_V01'),
    ],
  },
  {
    id: 'hr',
    label: 'RH',
    shortLabel: 'RH',
    description: 'Classement de contrats, fiches de paie, attestations, entretiens, formations et dossiers collaborateurs.',
    recommendedFor: ['RH', 'gestionnaires paie', 'office managers'],
    entityImportLabel: 'Importer des collaborateurs / services / départements',
    defaultSeparator: '_',
    entityTypes: [
      entity('employee', 'Collaborateur', 'Collaborateurs'),
      entity('department', 'Département', 'Départements'),
      entity('service', 'Service', 'Services'),
      entity('manager', 'Manager', 'Managers'),
      entity('site', 'Site', 'Sites'),
      entity('team', 'Équipe', 'Équipes'),
    ],
    fields: [
      field('entity', 'Collaborateur, service ou département', 'entity', 'COLLABORATEUR', true),
      field('department', 'Département', 'free-text', 'RH'),
      field('year', 'Année', 'number', '2026'),
      field('month', 'Mois', 'number', '05'),
      field('docType', 'Type de document', 'document-type', 'FDP', true),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoyé', 'free-text'),
    ],
    documentTypes: [
      doc('employment-contract', 'Contrat de travail', 'CTR_TRAV', 'Contrat', ['contrat', 'contrat travail']),
      doc('amendment', 'Avenant', 'AVT', 'Contrat', ['avenant contrat']),
      doc('pay-slip', 'Fiche de paie', 'FDP', 'Paie', ['bulletin de paie', 'paie']),
      doc('attestation', 'Attestation', 'ATT', 'Administratif', ['certificat']),
      doc('certificate', 'Certificat', 'CERTIF', 'Administratif'),
      doc('annual-review', 'Entretien annuel', 'EA', 'Suivi', ['evaluation annuelle']),
      doc('training', 'Formation', 'FORM', 'Formation', ['formation professionnelle']),
      doc('convocation', 'Convocation', 'CONVOC', 'Administratif'),
      doc('absence', 'Absence', 'ABS', 'Temps', ['conge']),
      doc('leave', 'Congé', 'CONGE', 'Temps'),
      doc('hr-note', 'Note RH', 'NOTE_RH', 'Interne', ['note ressources humaines']),
      doc('employee-file', 'Dossier collaborateur', 'DOS_COLLAB', 'Dossier', ['dossier salarie']),
      doc('evaluation', 'Évaluation', 'EVAL', 'Suivi'),
      doc('disciplinary', 'Document disciplinaire', 'DISC', 'Juridique'),
      doc('internal-policy', 'Politique interne', 'POL_INT', 'Interne'),
      doc('hr-procedure', 'Procédure RH', 'PROC_RH', 'Interne'),
    ],
    statuses: [...genericStatuses, doc('signed', 'Signé', 'SIGNE'), doc('pending', 'En attente', 'ATTENTE')],
    templates: [
      template('hr-employee-file', 'Dossier collaborateur', 'Structure centrée collaborateur.', ['entity', 'year', 'docType', 'version'], 'COLLABORATEUR_2026_FDP_V01'),
      template('hr-annual', 'Suivi annuel', 'Documents rattachés à une année RH.', ['department', 'entity', 'year', 'docType'], 'RH_COLLABORATEUR_2026_EA'),
      template('hr-training', 'Formation', 'Suivi des formations.', ['entity', 'docType', 'date', 'version'], 'COLLABORATEUR_FORM_20260515_V01'),
      template('hr-contracts', 'Contrats et avenants', 'Contrats, avenants et statuts de signature.', ['entity', 'docType', 'date', 'status'], 'COLLABORATEUR_CTR_TRAV_20260515_SIGNE'),
      template('custom', 'Convention personnalisée', 'Base libre à adapter.', ['entity', 'docType', 'date', 'version'], 'COLLABORATEUR_TYPE_DATE_V01'),
    ],
  },
  {
    id: 'healthcare',
    label: 'Santé',
    shortLabel: 'Santé',
    description: 'Classement de procédures, protocoles, documents qualité, audits internes et dossiers anonymisés.',
    recommendedFor: ['services qualité', 'établissements de santé', 'responsables de service'],
    entityImportLabel: 'Importer des services / unités',
    defaultSeparator: '_',
    entityTypes: [
      entity('service', 'Service', 'Services'),
      entity('pole', 'Pôle', 'Pôles'),
      entity('facility', 'Établissement', 'Établissements'),
      entity('unit', 'Unité', 'Unités'),
      entity('referent', 'Référent', 'Référents'),
      entity('quality-category', 'Catégorie qualité', 'Catégories qualité'),
    ],
    fields: [
      field('entity', 'Service ou unité', 'entity', 'SERVICE', true),
      field('facility', 'Établissement', 'free-text', 'ETABLISSEMENT'),
      field('docType', 'Type de document', 'document-type', 'PROC', true),
      field('reference', 'Référence', 'free-text', 'REF'),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoyé', 'free-text'),
    ],
    documentTypes: [
      doc('procedure', 'Procédure', 'PROC', 'Qualité', ['procedure']),
      doc('protocol', 'Protocole', 'PROTO', 'Médical', ['protocol']),
      doc('minutes', 'Compte rendu', 'CR', 'Suivi', ['compte-rendu']),
      doc('quality-report', 'Rapport qualité', 'RAP_QUAL', 'Qualité', ['rapport qualite']),
      doc('internal-audit', 'Audit interne', 'AUDIT_INT', 'Qualité', ['audit']),
      doc('action-plan', 'Plan d’action', 'PA', 'Qualité', ['plan action']),
      doc('admin-document', 'Document administratif', 'DOC_ADMIN', 'Administratif', ['administratif']),
      doc('anonymized-patient-sheet', 'Fiche patient anonymisée', 'FPA', 'Dossier', ['fiche patient anonymisee']),
      doc('service-note', 'Note de service', 'NOTE_SERV', 'Interne'),
      doc('form', 'Formulaire', 'FORM', 'Administratif'),
      doc('traceability', 'Traçabilité', 'TRACE', 'Qualité'),
      doc('checklist', 'Check-list', 'CHECK', 'Qualité'),
      doc('incident-report', 'Rapport d’incident', 'RAP_INC', 'Qualité'),
      doc('training-document', 'Document de formation', 'DOC_FORM', 'Formation'),
      doc('internal-notice', 'Notice interne', 'NOTICE_INT', 'Interne'),
    ],
    statuses: [...genericStatuses, doc('applicable', 'Applicable', 'APPLICABLE'), doc('obsolete', 'Obsolète', 'OBSOLETE')],
    templates: [
      template('health-quality', 'Qualité', 'Structure service, date, type, référence et version.', ['entity', 'date', 'docType', 'reference', 'version'], 'SERVICE_20260515_PROC_REF_V01'),
      template('health-procedures', 'Procédures internes', 'Structure établissement, service et statut.', ['facility', 'entity', 'docType', 'status', 'version'], 'ETABLISSEMENT_SERVICE_PROC_VALIDE_V01'),
      template('health-service', 'Service medical', 'Classement par service et type de document.', ['entity', 'docType', 'date', 'reference'], 'SERVICE_PROTO_20260515_REF'),
      template('health-audit', 'Audit interne', 'Classement des audits et plans d’action.', ['entity', 'docType', 'date', 'status'], 'SERVICE_AUDIT_INT_20260515_FINAL'),
      template('custom', 'Convention personnalisée', 'Base libre à adapter.', ['entity', 'docType', 'reference', 'version'], 'SERVICE_TYPE_REF_V01'),
    ],
  },
  {
    id: 'administration',
    label: 'Administratif / Secrétariat',
    shortLabel: 'Admin',
    description: 'Classement de courriers, notes internes, comptes rendus, suivis, archives et dossiers internes.',
    recommendedFor: ['secrétariats', 'assistants', 'services administratifs'],
    entityImportLabel: 'Importer des services / dossiers',
    defaultSeparator: '_',
    entityTypes: [
      entity('service', 'Service', 'Services'),
      entity('contact', 'Interlocuteur', 'Interlocuteurs'),
      entity('folder', 'Dossier', 'Dossiers'),
      entity('internal-ref', 'Référence interne', 'Références internes'),
      entity('department', 'Département', 'Départements'),
    ],
    fields: [
      field('entity', 'Service, interlocuteur ou dossier', 'entity', 'SERVICE', true),
      field('docType', 'Type de document', 'document-type', 'COUR', true),
      field('subject', 'Objet', 'free-text', 'OBJET'),
      field('reference', 'Référence', 'free-text', 'REF'),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoyé', 'free-text'),
    ],
    documentTypes: [
      doc('mail', 'Courrier', 'COUR', 'Courrier', ['lettre']),
      doc('email-export', 'Courriel exporté', 'MAIL_EXP', 'Courrier'),
      doc('minutes', 'Compte rendu', 'CR', 'Réunion', ['compte-rendu']),
      doc('internal-note', 'Note interne', 'NOTE_INT', 'Interne', ['note']),
      doc('pv', 'Procès-verbal', 'PV', 'Réunion', ['proces verbal']),
      doc('folder', 'Dossier', 'DOS', 'Dossier', ['dossier administratif']),
      doc('form', 'Formulaire', 'FORM', 'Administratif'),
      doc('archive', 'Archive', 'ARCH', 'Archive', ['archives']),
      doc('tracking', 'Suivi', 'SUIVI', 'Suivi', ['tableau de suivi']),
      doc('list', 'Liste', 'LISTE', 'Suivi'),
      doc('table', 'Tableau', 'TAB', 'Suivi'),
      doc('convocation', 'Convocation', 'CONVOC', 'Réunion'),
      doc('agenda', 'Ordre du jour', 'ODJ', 'Réunion'),
      doc('summary', 'Synthèse', 'SYNTHESE', 'Reporting'),
      doc('admin-report', 'Rapport administratif', 'RAP_ADMIN', 'Reporting'),
    ],
    statuses: genericStatuses,
    templates: [
      template('admin-mail', 'Courriers', 'Classement par service, date, type, objet et référence.', ['entity', 'date', 'docType', 'subject', 'reference'], 'SERVICE_20260515_COUR_OBJET_REF'),
      template('admin-minutes', 'Comptes rendus', 'Structure pour réunions et suivis.', ['entity', 'docType', 'date', 'status'], 'SERVICE_CR_20260515_VALIDE'),
      template('admin-archives', 'Archives internes', 'Structure dossier, type et date.', ['entity', 'docType', 'date', 'reference'], 'DOSSIER_ARCH_20260515_REF'),
      template('admin-tracking', 'Suivi de dossiers', 'Structure dossier, type, date et statut.', ['entity', 'docType', 'date', 'status'], 'DOSSIER_SUIVI_20260515_VALIDE'),
      template('custom', 'Convention personnalisée', 'Base libre à adapter.', ['entity', 'docType', 'date', 'reference'], 'DOSSIER_TYPE_DATE_REF'),
    ],
  },
  {
    id: 'legal',
    label: 'Juridique',
    shortLabel: 'Juridique',
    description: 'Classement de contrats, avenants, pièces, dossiers clients, procédures et courriers juridiques.',
    recommendedFor: ['juristes', 'avocats', 'directions juridiques'],
    entityImportLabel: 'Importer des clients / dossiers',
    defaultSeparator: '_',
    entityTypes: [
      entity('client', 'Client', 'Clients'),
      entity('case', 'Dossier', 'Dossiers'),
      entity('party', 'Partie', 'Parties'),
      entity('court', 'Juridiction', 'Juridictions'),
      entity('reference', 'Référence', 'Références'),
      entity('procedure-type', 'Type de procédure', 'Types de procédure'),
    ],
    fields: [
      field('entity', 'Client ou dossier', 'entity', 'CLIENT', true),
      field('case', 'Dossier', 'free-text', 'DOSSIER'),
      field('docType', 'Type de document', 'document-type', 'CTR', true),
      field('reference', 'Référence', 'free-text', 'REF'),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoyé', 'free-text'),
    ],
    documentTypes: [
      doc('contract', 'Contrat', 'CTR', 'Contrat', ['contract']),
      doc('amendment', 'Avenant', 'AVT', 'Contrat', ['avenant contrat']),
      doc('piece', 'Pièce', 'PIECE', 'Procédure', ['annexe']),
      doc('annex', 'Annexe', 'ANNEXE', 'Procédure'),
      doc('client-file', 'Dossier client', 'DOS_CLIENT', 'Dossier', ['dossier']),
      doc('legal-mail', 'Courrier juridique', 'COUR_JUR', 'Courrier', ['courrier']),
      doc('legal-note', 'Note juridique', 'NOTE_JUR', 'Interne', ['note']),
      doc('procedure', 'Procédure', 'PROC', 'Procédure', ['procedure']),
      doc('decision', 'Décision', 'DECISION', 'Procédure'),
      doc('summons', 'Assignation', 'ASSIGN', 'Procédure'),
      doc('pleadings', 'Conclusions', 'CONCL', 'Procédure'),
      doc('mandate', 'Mandat', 'MANDAT', 'Mandat'),
      doc('power', 'Pouvoir', 'POUVOIR', 'Mandat'),
      doc('notification', 'Notification', 'NOTIF', 'Courrier'),
      doc('proof', 'Preuve', 'PREUVE', 'Procédure'),
      doc('consultation', 'Consultation', 'CONSULT', 'Conseil'),
    ],
    statuses: [...genericStatuses, doc('signed', 'Signé', 'SIGNE'), doc('served', 'Notifié', 'NOTIFIE')],
    templates: [
      template('legal-acts', 'Actes de cession', 'Convention pour actes de cession, vente et transmission.', ['entity', 'case', 'docType', 'date', 'reference', 'version'], 'CLIENT_DOSSIER_ACTE_20260515_REF_V01'),
      template('legal-client', 'Dossier client', 'Structure client, dossier, type, date et version.', ['entity', 'case', 'docType', 'date', 'version'], 'CLIENT_DOSSIER_CTR_20260515_V01'),
      template('legal-contracts', 'Contrats', 'Structure contrat et référence.', ['entity', 'docType', 'reference', 'status', 'version'], 'CLIENT_CTR_REF_SIGNE_V01'),
      template('legal-procedure', 'Procedures', 'Structure dossier, type, référence et statut.', ['case', 'docType', 'reference', 'status'], 'DOSSIER_PROC_REF_VALIDE'),
      template('legal-pieces', 'Pieces', 'Classement de pièces et annexes.', ['case', 'docType', 'reference', 'version'], 'DOSSIER_PIECE_REF_V01'),
      template('custom', 'Convention personnalisée', 'Base libre à adapter.', ['entity', 'docType', 'reference', 'version'], 'CLIENT_TYPE_REF_V01'),
    ],
  },
  {
    id: 'industry',
    label: 'Industrie',
    shortLabel: 'Industrie',
    description: 'Classement de fiches techniques, procédures, qualité, maintenance, contrôles et documentation équipement.',
    recommendedFor: ['qualité', 'maintenance', 'production', 'méthodes'],
    entityImportLabel: 'Importer des sites / équipements',
    defaultSeparator: '_',
    entityTypes: [
      entity('site', 'Site', 'Sites'),
      entity('line', 'Ligne', 'Lignes'),
      entity('equipment', 'Équipement', 'Équipements'),
      entity('machine', 'Machine', 'Machines'),
      entity('product-ref', 'Référence produit', 'Références produit'),
      entity('workshop', 'Atelier', 'Ateliers'),
      entity('zone', 'Zone', 'Zones'),
    ],
    fields: [
      field('site', 'Site', 'entity', 'SITE', true),
      field('equipment', 'Équipement ou machine', 'entity', 'EQP'),
      field('line', 'Ligne ou atelier', 'free-text', 'LIGNE'),
      field('docType', 'Type de document', 'document-type', 'FT', true),
      field('reference', 'Référence', 'free-text', 'REF'),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoyé', 'free-text'),
    ],
    documentTypes: [
      doc('technical-sheet', 'Fiche technique', 'FT', 'Technique', ['fiche produit']),
      doc('procedure', 'Procédure', 'PROC', 'Process', ['procedure']),
      doc('quality-report', 'Rapport qualité', 'RAP_QUAL', 'Qualité', ['rapport qualite']),
      doc('control', 'Contrôle', 'CTRL', 'Contrôle', ['controle']),
      doc('maintenance', 'Maintenance', 'MAINT', 'Maintenance', ['rapport maintenance']),
      doc('notice', 'Notice', 'NOTICE', 'Technique', ['manuel']),
      doc('intervention-plan', 'Plan d’intervention', 'PI', 'Maintenance', ['plan intervention']),
      doc('non-conformity', 'Non-conformité', 'NC', 'Qualité', ['non conformite']),
      doc('equipment-sheet', 'Fiche équipement', 'FE', 'Équipement'),
      doc('test-report', 'Rapport de test', 'RAP_TEST', 'Qualité'),
      doc('certificate', 'Certificat', 'CERTIF', 'Qualité'),
      doc('prevention-plan', 'Plan de prévention', 'PP', 'Sécurité'),
      doc('operating-mode', 'Mode opératoire', 'MO', 'Process'),
      doc('checklist', 'Check-list', 'CHECK', 'Contrôle'),
      doc('incident-report', 'Rapport incident', 'RAP_INC', 'Sécurité'),
      doc('product-documentation', 'Documentation produit', 'DOC_PROD', 'Technique'),
    ],
    statuses: [...genericStatuses, doc('controlled', 'Contrôle', 'CONTROLE'), doc('non-compliant', 'Non conforme', 'NC')],
    templates: [
      template('industry-maintenance', 'Maintenance', 'Structure site, équipement, type, date et version.', ['site', 'equipment', 'docType', 'date', 'version'], 'SITE_EQP_MAINT_20260515_V01'),
      template('industry-quality', 'Qualité', 'Structure ligne, référence, type et statut.', ['line', 'reference', 'docType', 'status', 'version'], 'LIGNE_REF_RAP_QUAL_VALIDE_V01'),
      template('industry-equipment', 'Documentation equipement', 'Documentation rattachée à un équipement.', ['site', 'equipment', 'docType', 'reference', 'version'], 'SITE_EQP_FT_REF_V01'),
      template('industry-control', 'Contrôle', 'Contrôles, checklists et rapports.', ['site', 'line', 'docType', 'date', 'status'], 'SITE_LIGNE_CTRL_20260515_VALIDE'),
      template('custom', 'Convention personnalisée', 'Base libre à adapter.', ['site', 'docType', 'reference', 'version'], 'SITE_TYPE_REF_V01'),
    ],
  },
  {
    id: 'real-estate',
    label: 'Immobilier',
    shortLabel: 'Immobilier',
    description: 'Classement de baux, états des lieux, diagnostics, quittances, dossiers bien et gestion locative.',
    recommendedFor: ['agences', 'gestionnaires locatifs', 'asset managers', 'syndics'],
    entityImportLabel: 'Importer des biens / locataires',
    defaultSeparator: '_',
    entityTypes: [
      entity('property', 'Bien', 'Biens'),
      entity('address', 'Adresse simplifiée', 'Adresses simplifiées'),
      entity('tenant', 'Locataire', 'Locataires'),
      entity('lessor', 'Bailleur', 'Bailleurs'),
      entity('agency', 'Agence', 'Agences'),
      entity('folder', 'Dossier', 'Dossiers'),
      entity('lot', 'Lot immobilier', 'Lots immobiliers'),
    ],
    fields: [
      field('property', 'Bien ou adresse', 'entity', 'BIEN', true),
      field('tenant', 'Locataire ou bailleur', 'entity', 'LOCATAIRE'),
      field('docType', 'Type de document', 'document-type', 'BAIL', true),
      field('reference', 'Référence', 'free-text', 'REF'),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoyé', 'free-text'),
    ],
    documentTypes: [
      doc('lease', 'Bail', 'BAIL', 'Location', ['contrat de bail']),
      doc('inventory', 'État des lieux', 'EDL', 'Location', ['etat des lieux']),
      doc('mandate', 'Mandat', 'MANDAT', 'Gestion', ['mandat gestion']),
      doc('diagnostic', 'Diagnostic', 'DIAG', 'Technique', ['diagnostic immobilier']),
      doc('invoice', 'Facture', 'FAC', 'Comptabilité', ['invoice']),
      doc('receipt', 'Quittance', 'QUIT', 'Location', ['quittance loyer']),
      doc('tenant-mail', 'Courrier locataire', 'COUR_LOC', 'Courrier', ['courrier']),
      doc('property-file', 'Dossier bien', 'DOS_BIEN', 'Dossier', ['dossier immobilier']),
      doc('visit-minutes', 'Compte rendu visite', 'CR_VISITE', 'Commercial'),
      doc('insurance-certificate', 'Attestation assurance', 'ATT_ASSUR', 'Administratif'),
      doc('fund-call', 'Appel de fonds', 'ADF', 'Copropriété'),
      doc('ag-minutes', 'Procès-verbal AG', 'PV_AG', 'Copropriété'),
      doc('copro-rules', 'Règlement copropriété', 'REG_COPRO', 'Copropriété'),
      doc('plan', 'Plan', 'PLAN', 'Technique'),
      doc('photo', 'Photo', 'PHOTO', 'Média'),
      doc('works-quote', 'Devis travaux', 'DEVIS_TRAV', 'Travaux'),
      doc('technical-report', 'Rapport technique', 'RAP_TECH', 'Technique'),
    ],
    statuses: [...genericStatuses, doc('signed', 'Signé', 'SIGNE'), doc('pending', 'En attente', 'ATTENTE')],
    templates: [
      template('real-estate-property', 'Dossier bien', 'Structure bien, type, date et référence.', ['property', 'docType', 'date', 'reference', 'version'], 'BIEN_BAIL_20260515_REF_V01'),
      template('real-estate-rental', 'Gestion locative', 'Structure locataire, bien, type et date.', ['tenant', 'property', 'docType', 'date'], 'LOCATAIRE_BIEN_QUIT_20260515'),
      template('real-estate-copro', 'Copropriété', 'Structure bien et documents de copropriété.', ['property', 'docType', 'date', 'reference'], 'BIEN_PV_AG_20260515_REF'),
      template('real-estate-works', 'Travaux', 'Structure bien, travaux et référence.', ['property', 'docType', 'reference', 'version'], 'BIEN_DEVIS_TRAV_REF_V01'),
      template('custom', 'Convention personnalisée', 'Base libre à adapter.', ['property', 'docType', 'date', 'reference'], 'BIEN_TYPE_DATE_REF'),
    ],
  },
  {
    id: 'custom',
    label: 'Convention personnalisée',
    shortLabel: 'Custom',
    description: 'Profil générique pour composer vos propres champs, entités et conventions sans vocabulaire métier imposé.',
    recommendedFor: ['équipes avec convention interne spécifique'],
    entityImportLabel: 'Importer des entités',
    defaultSeparator: '_',
    entityTypes: [entity('entity', 'Entité', 'Entités')],
    fields: [
      field('entity', 'Entité', 'entity', 'ENTITE'),
      field('custom1', 'Champ 1', 'free-text', 'CHAMP1'),
      field('custom2', 'Champ 2', 'free-text', 'CHAMP2'),
      field('docType', 'Type de document', 'document-type', 'TYPE'),
      field('date', 'Date', 'date'),
      field('reference', 'Référence', 'free-text', 'REF'),
      field('status', 'Statut', 'status', 'STATUT'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoyé', 'free-text'),
    ],
    documentTypes: [
      doc('document', 'Document', 'DOC'),
      doc('report', 'Rapport', 'RAP'),
      doc('note', 'Note', 'NOTE'),
      doc('record', 'Compte rendu', 'CR'),
      doc('form', 'Formulaire', 'FORM'),
    ],
    statuses: genericStatuses,
    templates: [
      template('custom-basic', 'Convention personnalisée', 'Base générique sans vocabulaire métier imposé.', ['entity', 'docType', 'reference', 'version'], 'ENTITE_TYPE_REF_V01'),
    ],
  },
];
