import type {
  DocumentTypeDefinition,
  EntityTypeDefinition,
  IndustryProfile,
  NamingField,
  NamingTemplate,
} from './types';

const doc = (
  id: string,
  label: string,
  abbreviation: string,
  category?: string,
  aliases: string[] = [],
): DocumentTypeDefinition => ({ id, label, abbreviation, category, aliases });

const entity = (id: string, label: string, pluralLabel: string, examples: string[] = []): EntityTypeDefinition => ({
  id,
  label,
  pluralLabel,
  examples,
});

const field = (
  id: string,
  label: string,
  kind: NamingField['kind'],
  placeholder?: string,
  required = false,
  examples: string[] = [],
): NamingField => ({ id, label, kind, placeholder, required, examples });

const template = (
  id: string,
  label: string,
  description: string,
  fields: string[],
  example: string,
  defaultSeparator: '_' | '-' | '.' = '_',
  disclaimer = 'Template de depart a adapter a votre convention interne.',
): NamingTemplate => ({ id, label, description, fields, example, defaultSeparator, disclaimer });

const genericStatuses = [
  doc('draft', 'Brouillon', 'BROUILLON'),
  doc('valid', 'Valide', 'VALIDE', undefined, ['valide']),
  doc('final', 'Final', 'FINAL'),
  doc('archived', 'Archive', 'ARCHIVE', undefined, ['archive']),
];

export const INDUSTRY_PROFILES: IndustryProfile[] = [
  {
    id: 'bim-construction',
    label: 'BIM / Construction',
    shortLabel: 'BIM',
    description: 'Conventions de nommage pour livrables BIM, plans, maquettes, rapports techniques et depots CDE.',
    recommendedFor: ['BIM managers', 'coordinateurs BIM', 'architectes', 'bureaux d etudes', 'entreprises generales'],
    entityImportLabel: 'Importer des entreprises / emetteurs',
    defaultSeparator: '_',
    entityTypes: [
      entity('company', 'Entreprise', 'Entreprises'),
      entity('originator', 'Emetteur', 'Emetteurs'),
      entity('engineering-office', 'Bureau d etudes', 'Bureaux d etudes'),
      entity('architect', 'Architecte', 'Architectes'),
      entity('client', 'Client', 'Clients'),
      entity('agent', 'Mandataire', 'Mandataires'),
      entity('lot', 'Lot', 'Lots'),
      entity('discipline', 'Discipline', 'Disciplines'),
    ],
    fields: [
      field('project', 'Projet', 'free-text', 'PROJET', true),
      field('building', 'Batiment', 'free-text', 'BAT'),
      field('originator', 'Emetteur', 'entity', 'BET'),
      field('company', 'Entreprise', 'entity', 'ENT'),
      field('zone', 'Zone', 'free-text', 'ZN01'),
      field('level', 'Niveau', 'free-text', 'NIV01'),
      field('discipline', 'Discipline', 'select', 'ARC'),
      field('workLot', 'Lot', 'select', 'CVC'),
      field('docType', 'Type de document', 'document-type', 'PLAN', true),
      field('sequence', 'Numero', 'number', '001'),
      field('revision', 'Revision', 'revision', 'REV01'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('filename', 'Nom original nettoye', 'free-text'),
    ],
    documentTypes: [
      doc('plan', 'Plan', 'PLAN', 'Plan', ['plans']),
      doc('section', 'Coupe', 'COUPE', 'Plan', ['coupes']),
      doc('facade', 'Facade', 'FACADE', 'Plan', ['facade', 'facades']),
      doc('detail', 'Detail', 'DETAIL', 'Plan'),
      doc('digital-model', 'Maquette numerique', 'MN', 'Maquette', ['maquette', 'maquette bim', 'model']),
      doc('ifc', 'Fichier IFC', 'IFC', 'Maquette'),
      doc('dwg', 'Fichier DWG', 'DWG', 'CAO'),
      doc('bim-report', 'Rapport BIM', 'RAP_BIM', 'Coordination'),
      doc('synthesis-report', 'Rapport de synthese', 'RAP_SYN', 'Coordination'),
      doc('calculation-note', 'Note de calcul', 'NDC', 'Technique', ['notes de calcul']),
      doc('technical-sheet', 'Fiche technique', 'FT', 'Technique', ['fiche produit']),
      doc('transmittal', 'Bordereau', 'BORD', 'Diffusion', ['bordereau de diffusion']),
      doc('schedule', 'Planning', 'PLANNING', 'Projet'),
      doc('minutes', 'Compte rendu', 'CR', 'Projet', ['compte-rendu']),
      doc('site-minutes', 'Compte rendu chantier', 'CR_CHANTIER', 'Projet'),
      doc('pv', 'Proces-verbal', 'PV', 'Projet', ['proces verbal', 'proces-verbal']),
      doc('notice', 'Notice', 'NOTICE', 'Technique'),
      doc('as-built', 'Dossier des ouvrages executes', 'DOE', 'Livraison'),
      doc('visa', 'Visa', 'VISA', 'Validation'),
      doc('observation', 'Fiche observation', 'FO', 'Controle'),
      doc('control-report', 'Rapport de controle', 'RAP_CTRL', 'Controle'),
      doc('technical-document', 'Document technique', 'DOCTECH', 'Technique', ['documents techniques', 'doc technique', 'documentation technique']),
    ],
    statuses: [
      doc('s0', 'Travail en cours', 'S0'),
      doc('s1', 'Partage', 'S1'),
      doc('a1', 'Approuve', 'A1'),
      doc('rev', 'Revision', 'REV'),
      ...genericStatuses,
    ],
    templates: [
      template('cde-delivery', 'Livraison CDE', 'Structure simple pour lots de fichiers avant depot.', ['project', 'building', 'workLot', 'docType', 'company', 'sequence'], 'PROJET_BAT_CVC_PLAN_ENT_001'),
      template('iso19650', 'ISO 19650 inspire', 'Structure inspiree de pratiques ISO 19650.', ['project', 'originator', 'discipline', 'zone', 'docType', 'sequence', 'revision'], 'PROJET-ORG-ARC-ZN01-PLAN-001-P01', '-', 'Template inspire de pratiques de nommage BIM. Ne constitue pas une certification.'),
      template('swiss-bim', 'SIA inspire', 'Structure inspiree de conventions BIM suisses.', ['project', 'building', 'discipline', 'docType', 'sequence', 'revision'], 'PROJET_BAT_ARC_PLAN_001_A', '_', 'Template inspire de pratiques de nommage BIM. Ne constitue pas une certification.'),
      template('french-bim', 'BIM France inspire', 'Structure projet, phase, discipline et type.', ['project', 'building', 'discipline', 'docType', 'level', 'sequence'], 'PROJET-BAT-ARC-PLAN-NIV01-001', '-', 'Template inspire de pratiques de nommage BIM. Ne constitue pas une certification.'),
      template('custom', 'Convention projet personnalisee', 'Base libre a adapter au protocole projet.', ['project', 'docType', 'sequence', 'revision'], 'PROJET_PLAN_001_REV01'),
    ],
    disclaimers: ['Les templates BIM fournis sont des points de depart, pas des certifications de conformite.'],
  },
  {
    id: 'finance',
    label: 'Finance',
    shortLabel: 'Finance',
    description: 'Classement de factures, justificatifs, rapports financiers, budgets, clotures et pieces comptables.',
    recommendedFor: ['comptables', 'controleurs de gestion', 'DAF', 'cabinets d audit'],
    entityImportLabel: 'Importer des clients / fournisseurs / entites',
    defaultSeparator: '_',
    entityTypes: [
      entity('client', 'Client', 'Clients'),
      entity('supplier', 'Fournisseur', 'Fournisseurs'),
      entity('entity', 'Entite', 'Entites'),
      entity('company', 'Societe', 'Societes'),
      entity('cost-center', 'Centre de cout', 'Centres de cout'),
      entity('fiscal-year', 'Exercice', 'Exercices'),
      entity('finance-service', 'Service financier', 'Services financiers'),
    ],
    fields: [
      field('entity', 'Client, fournisseur ou entite', 'entity', 'CLIENT', true),
      field('year', 'Annee', 'number', '2026'),
      field('month', 'Mois', 'number', '05'),
      field('docType', 'Type de document', 'document-type', 'FAC', true),
      field('reference', 'Reference', 'free-text', 'REF'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoye', 'free-text'),
    ],
    documentTypes: [
      doc('invoice', 'Facture', 'FAC', 'Comptabilite', ['invoice']),
      doc('credit-note', 'Avoir', 'AVOIR', 'Comptabilite', ['note de credit']),
      doc('quote', 'Devis', 'DEVIS', 'Vente'),
      doc('purchase-order', 'Bon de commande', 'BC', 'Achat'),
      doc('bank-statement', 'Releve bancaire', 'RELBQ', 'Banque', ['releve bancaire']),
      doc('supporting-document', 'Justificatif', 'JUSTIF', 'Comptabilite', ['piece justificative', 'piece justificative']),
      doc('financial-report', 'Rapport financier', 'RAPFIN', 'Reporting', ['reporting financier']),
      doc('budget', 'Budget', 'BUDGET', 'Reporting', ['previsionnel', 'budget previsionnel']),
      doc('closing', 'Cloture', 'CLOTURE', 'Comptabilite', ['closing']),
      doc('audit', 'Audit', 'AUDIT', 'Audit', ['rapport audit']),
      doc('expense-report', 'Note de frais', 'NDF', 'Frais', ['frais']),
      doc('contract', 'Contrat', 'CTR', 'Contrat', ['contract']),
      doc('schedule', 'Echeancier', 'ECH', 'Suivi'),
      doc('tracking-table', 'Tableau de suivi', 'SUIVI', 'Suivi'),
      doc('trial-balance', 'Balance', 'BALANCE', 'Comptabilite'),
      doc('ledger', 'Grand livre', 'GL', 'Comptabilite'),
      doc('accounting-export', 'Export comptable', 'EXP_COMPTA', 'Comptabilite'),
      doc('declaration', 'Declaration', 'DECL', 'Fiscal'),
      doc('bank-reconciliation', 'Rapprochement bancaire', 'RAPP_BQ', 'Banque'),
    ],
    statuses: [...genericStatuses, doc('paid', 'Paye', 'PAYE'), doc('pending', 'En attente', 'ATTENTE')],
    templates: [
      template('finance-monthly', 'Classement mensuel', 'Classement par entite, periode, type et reference.', ['entity', 'year', 'month', 'docType', 'reference', 'status'], 'ENTITE_2026_05_FAC_REF_VALIDE'),
      template('finance-client', 'Dossier client', 'Structure orientee client et exercice.', ['entity', 'year', 'docType', 'reference', 'version'], 'CLIENT_2026_RAPFIN_REF_V01'),
      template('finance-audit', 'Audit financier', 'Structure pour pieces et livrables d audit.', ['entity', 'year', 'docType', 'reference', 'status', 'version'], 'CLIENT_2026_AUDIT_REF_FINAL_V01'),
      template('finance-pieces', 'Pieces comptables', 'Structure simple pour factures et justificatifs.', ['entity', 'year', 'month', 'docType', 'reference'], 'FOURNISSEUR_2026_05_FAC_REF'),
      template('custom', 'Convention personnalisee', 'Base libre a adapter.', ['entity', 'docType', 'reference', 'version'], 'ENTITE_TYPE_REF_V01'),
    ],
  },
  {
    id: 'hr',
    label: 'RH',
    shortLabel: 'RH',
    description: 'Classement de contrats, fiches de paie, attestations, entretiens, formations et dossiers collaborateurs.',
    recommendedFor: ['RH', 'gestionnaires paie', 'office managers'],
    entityImportLabel: 'Importer des collaborateurs / services / departements',
    defaultSeparator: '_',
    entityTypes: [
      entity('employee', 'Collaborateur', 'Collaborateurs'),
      entity('department', 'Departement', 'Departements'),
      entity('service', 'Service', 'Services'),
      entity('manager', 'Manager', 'Managers'),
      entity('site', 'Site', 'Sites'),
      entity('team', 'Equipe', 'Equipes'),
    ],
    fields: [
      field('entity', 'Collaborateur, service ou departement', 'entity', 'COLLABORATEUR', true),
      field('department', 'Departement', 'free-text', 'RH'),
      field('year', 'Annee', 'number', '2026'),
      field('month', 'Mois', 'number', '05'),
      field('docType', 'Type de document', 'document-type', 'FDP', true),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoye', 'free-text'),
    ],
    documentTypes: [
      doc('employment-contract', 'Contrat de travail', 'CTR_TRAV', 'Contrat', ['contrat', 'contrat travail']),
      doc('amendment', 'Avenant', 'AVT', 'Contrat', ['avenant contrat']),
      doc('pay-slip', 'Fiche de paie', 'FDP', 'Paie', ['bulletin de paie', 'paie']),
      doc('attestation', 'Attestation', 'ATT', 'Administratif', ['certificat']),
      doc('certificate', 'Certificat', 'CERTIF', 'Administratif'),
      doc('annual-review', 'Entretien annuel', 'EA', 'Suivi', ['evaluation annuelle']),
      doc('training', 'Formation', 'FORM', 'Formation', ['formation professionnelle']),
      doc('convocation', 'Convocation', 'CONVOC', 'Administratif'),
      doc('absence', 'Absence', 'ABS', 'Temps', ['conge']),
      doc('leave', 'Conge', 'CONGE', 'Temps'),
      doc('hr-note', 'Note RH', 'NOTE_RH', 'Interne', ['note ressources humaines']),
      doc('employee-file', 'Dossier collaborateur', 'DOS_COLLAB', 'Dossier', ['dossier salarie']),
      doc('evaluation', 'Evaluation', 'EVAL', 'Suivi'),
      doc('disciplinary', 'Document disciplinaire', 'DISC', 'Juridique'),
      doc('internal-policy', 'Politique interne', 'POL_INT', 'Interne'),
      doc('hr-procedure', 'Procedure RH', 'PROC_RH', 'Interne'),
    ],
    statuses: [...genericStatuses, doc('signed', 'Signe', 'SIGNE'), doc('pending', 'En attente', 'ATTENTE')],
    templates: [
      template('hr-employee-file', 'Dossier collaborateur', 'Structure centree collaborateur.', ['entity', 'year', 'docType', 'version'], 'COLLABORATEUR_2026_FDP_V01'),
      template('hr-annual', 'Suivi annuel', 'Documents rattaches a une annee RH.', ['department', 'entity', 'year', 'docType'], 'RH_COLLABORATEUR_2026_EA'),
      template('hr-training', 'Formation', 'Suivi des formations.', ['entity', 'docType', 'date', 'version'], 'COLLABORATEUR_FORM_20260515_V01'),
      template('hr-contracts', 'Contrats et avenants', 'Contrats, avenants et statuts de signature.', ['entity', 'docType', 'date', 'status'], 'COLLABORATEUR_CTR_TRAV_20260515_SIGNE'),
      template('custom', 'Convention personnalisee', 'Base libre a adapter.', ['entity', 'docType', 'date', 'version'], 'COLLABORATEUR_TYPE_DATE_V01'),
    ],
  },
  {
    id: 'healthcare',
    label: 'Sante',
    shortLabel: 'Sante',
    description: 'Classement de procedures, protocoles, documents qualite, audits internes et dossiers anonymises.',
    recommendedFor: ['services qualite', 'etablissements de sante', 'responsables de service'],
    entityImportLabel: 'Importer des services / unites',
    defaultSeparator: '_',
    entityTypes: [
      entity('service', 'Service', 'Services'),
      entity('pole', 'Pole', 'Poles'),
      entity('facility', 'Etablissement', 'Etablissements'),
      entity('unit', 'Unite', 'Unites'),
      entity('referent', 'Referent', 'Referents'),
      entity('quality-category', 'Categorie qualite', 'Categories qualite'),
    ],
    fields: [
      field('entity', 'Service ou unite', 'entity', 'SERVICE', true),
      field('facility', 'Etablissement', 'free-text', 'ETABLISSEMENT'),
      field('docType', 'Type de document', 'document-type', 'PROC', true),
      field('reference', 'Reference', 'free-text', 'REF'),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoye', 'free-text'),
    ],
    documentTypes: [
      doc('procedure', 'Procedure', 'PROC', 'Qualite', ['procedure']),
      doc('protocol', 'Protocole', 'PROTO', 'Medical', ['protocol']),
      doc('minutes', 'Compte rendu', 'CR', 'Suivi', ['compte-rendu']),
      doc('quality-report', 'Rapport qualite', 'RAP_QUAL', 'Qualite', ['rapport qualite']),
      doc('internal-audit', 'Audit interne', 'AUDIT_INT', 'Qualite', ['audit']),
      doc('action-plan', 'Plan d action', 'PA', 'Qualite', ['plan action']),
      doc('admin-document', 'Document administratif', 'DOC_ADMIN', 'Administratif', ['administratif']),
      doc('anonymized-patient-sheet', 'Fiche patient anonymisee', 'FPA', 'Dossier', ['fiche patient anonymisee']),
      doc('service-note', 'Note de service', 'NOTE_SERV', 'Interne'),
      doc('form', 'Formulaire', 'FORM', 'Administratif'),
      doc('traceability', 'Tracabilite', 'TRACE', 'Qualite'),
      doc('checklist', 'Check-list', 'CHECK', 'Qualite'),
      doc('incident-report', 'Rapport d incident', 'RAP_INC', 'Qualite'),
      doc('training-document', 'Document de formation', 'DOC_FORM', 'Formation'),
      doc('internal-notice', 'Notice interne', 'NOTICE_INT', 'Interne'),
    ],
    statuses: [...genericStatuses, doc('applicable', 'Applicable', 'APPLICABLE'), doc('obsolete', 'Obsolete', 'OBSOLETE')],
    templates: [
      template('health-quality', 'Qualite', 'Structure service, date, type, reference et version.', ['entity', 'date', 'docType', 'reference', 'version'], 'SERVICE_20260515_PROC_REF_V01'),
      template('health-procedures', 'Procedures internes', 'Structure etablissement, service et statut.', ['facility', 'entity', 'docType', 'status', 'version'], 'ETABLISSEMENT_SERVICE_PROC_VALIDE_V01'),
      template('health-service', 'Service medical', 'Classement par service et type de document.', ['entity', 'docType', 'date', 'reference'], 'SERVICE_PROTO_20260515_REF'),
      template('health-audit', 'Audit interne', 'Classement des audits et plans d action.', ['entity', 'docType', 'date', 'status'], 'SERVICE_AUDIT_INT_20260515_FINAL'),
      template('custom', 'Convention personnalisee', 'Base libre a adapter.', ['entity', 'docType', 'reference', 'version'], 'SERVICE_TYPE_REF_V01'),
    ],
  },
  {
    id: 'administration',
    label: 'Administratif / Secretariat',
    shortLabel: 'Admin',
    description: 'Classement de courriers, notes internes, comptes rendus, suivis, archives et dossiers internes.',
    recommendedFor: ['secretariats', 'assistants', 'services administratifs'],
    entityImportLabel: 'Importer des services / dossiers',
    defaultSeparator: '_',
    entityTypes: [
      entity('service', 'Service', 'Services'),
      entity('contact', 'Interlocuteur', 'Interlocuteurs'),
      entity('folder', 'Dossier', 'Dossiers'),
      entity('internal-ref', 'Reference interne', 'References internes'),
      entity('department', 'Departement', 'Departements'),
    ],
    fields: [
      field('entity', 'Service, interlocuteur ou dossier', 'entity', 'SERVICE', true),
      field('docType', 'Type de document', 'document-type', 'COUR', true),
      field('subject', 'Objet', 'free-text', 'OBJET'),
      field('reference', 'Reference', 'free-text', 'REF'),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoye', 'free-text'),
    ],
    documentTypes: [
      doc('mail', 'Courrier', 'COUR', 'Courrier', ['lettre']),
      doc('email-export', 'Courriel exporte', 'MAIL_EXP', 'Courrier'),
      doc('minutes', 'Compte rendu', 'CR', 'Reunion', ['compte-rendu']),
      doc('internal-note', 'Note interne', 'NOTE_INT', 'Interne', ['note']),
      doc('pv', 'Proces-verbal', 'PV', 'Reunion', ['proces verbal']),
      doc('folder', 'Dossier', 'DOS', 'Dossier', ['dossier administratif']),
      doc('form', 'Formulaire', 'FORM', 'Administratif'),
      doc('archive', 'Archive', 'ARCH', 'Archive', ['archives']),
      doc('tracking', 'Suivi', 'SUIVI', 'Suivi', ['tableau de suivi']),
      doc('list', 'Liste', 'LISTE', 'Suivi'),
      doc('table', 'Tableau', 'TAB', 'Suivi'),
      doc('convocation', 'Convocation', 'CONVOC', 'Reunion'),
      doc('agenda', 'Ordre du jour', 'ODJ', 'Reunion'),
      doc('summary', 'Synthese', 'SYNTHESE', 'Reporting'),
      doc('admin-report', 'Rapport administratif', 'RAP_ADMIN', 'Reporting'),
    ],
    statuses: genericStatuses,
    templates: [
      template('admin-mail', 'Courriers', 'Classement par service, date, type, objet et reference.', ['entity', 'date', 'docType', 'subject', 'reference'], 'SERVICE_20260515_COUR_OBJET_REF'),
      template('admin-minutes', 'Comptes rendus', 'Structure pour reunions et suivis.', ['entity', 'docType', 'date', 'status'], 'SERVICE_CR_20260515_VALIDE'),
      template('admin-archives', 'Archives internes', 'Structure dossier, type et date.', ['entity', 'docType', 'date', 'reference'], 'DOSSIER_ARCH_20260515_REF'),
      template('admin-tracking', 'Suivi de dossiers', 'Structure dossier, type, date et statut.', ['entity', 'docType', 'date', 'status'], 'DOSSIER_SUIVI_20260515_VALIDE'),
      template('custom', 'Convention personnalisee', 'Base libre a adapter.', ['entity', 'docType', 'date', 'reference'], 'DOSSIER_TYPE_DATE_REF'),
    ],
  },
  {
    id: 'legal',
    label: 'Juridique',
    shortLabel: 'Juridique',
    description: 'Classement de contrats, avenants, pieces, dossiers clients, procedures et courriers juridiques.',
    recommendedFor: ['juristes', 'avocats', 'directions juridiques'],
    entityImportLabel: 'Importer des clients / dossiers',
    defaultSeparator: '_',
    entityTypes: [
      entity('client', 'Client', 'Clients'),
      entity('case', 'Dossier', 'Dossiers'),
      entity('party', 'Partie', 'Parties'),
      entity('court', 'Juridiction', 'Juridictions'),
      entity('reference', 'Reference', 'References'),
      entity('procedure-type', 'Type de procedure', 'Types de procedure'),
    ],
    fields: [
      field('entity', 'Client ou dossier', 'entity', 'CLIENT', true),
      field('case', 'Dossier', 'free-text', 'DOSSIER'),
      field('docType', 'Type de document', 'document-type', 'CTR', true),
      field('reference', 'Reference', 'free-text', 'REF'),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoye', 'free-text'),
    ],
    documentTypes: [
      doc('contract', 'Contrat', 'CTR', 'Contrat', ['contract']),
      doc('amendment', 'Avenant', 'AVT', 'Contrat', ['avenant contrat']),
      doc('piece', 'Piece', 'PIECE', 'Procedure', ['annexe']),
      doc('annex', 'Annexe', 'ANNEXE', 'Procedure'),
      doc('client-file', 'Dossier client', 'DOS_CLIENT', 'Dossier', ['dossier']),
      doc('legal-mail', 'Courrier juridique', 'COUR_JUR', 'Courrier', ['courrier']),
      doc('legal-note', 'Note juridique', 'NOTE_JUR', 'Interne', ['note']),
      doc('procedure', 'Procedure', 'PROC', 'Procedure', ['procedure']),
      doc('decision', 'Decision', 'DECISION', 'Procedure'),
      doc('summons', 'Assignation', 'ASSIGN', 'Procedure'),
      doc('pleadings', 'Conclusions', 'CONCL', 'Procedure'),
      doc('mandate', 'Mandat', 'MANDAT', 'Mandat'),
      doc('power', 'Pouvoir', 'POUVOIR', 'Mandat'),
      doc('notification', 'Notification', 'NOTIF', 'Courrier'),
      doc('proof', 'Preuve', 'PREUVE', 'Procedure'),
      doc('consultation', 'Consultation', 'CONSULT', 'Conseil'),
    ],
    statuses: [...genericStatuses, doc('signed', 'Signe', 'SIGNE'), doc('served', 'Notifie', 'NOTIFIE')],
    templates: [
      template('legal-client', 'Dossier client', 'Structure client, dossier, type, date et version.', ['entity', 'case', 'docType', 'date', 'version'], 'CLIENT_DOSSIER_CTR_20260515_V01'),
      template('legal-contracts', 'Contrats', 'Structure contrat et reference.', ['entity', 'docType', 'reference', 'status', 'version'], 'CLIENT_CTR_REF_SIGNE_V01'),
      template('legal-procedure', 'Procedures', 'Structure dossier, type, reference et statut.', ['case', 'docType', 'reference', 'status'], 'DOSSIER_PROC_REF_VALIDE'),
      template('legal-pieces', 'Pieces', 'Classement de pieces et annexes.', ['case', 'docType', 'reference', 'version'], 'DOSSIER_PIECE_REF_V01'),
      template('custom', 'Convention personnalisee', 'Base libre a adapter.', ['entity', 'docType', 'reference', 'version'], 'CLIENT_TYPE_REF_V01'),
    ],
  },
  {
    id: 'industry',
    label: 'Industrie',
    shortLabel: 'Industrie',
    description: 'Classement de fiches techniques, procedures, qualite, maintenance, controles et documentation equipement.',
    recommendedFor: ['qualite', 'maintenance', 'production', 'methodes'],
    entityImportLabel: 'Importer des sites / equipements',
    defaultSeparator: '_',
    entityTypes: [
      entity('site', 'Site', 'Sites'),
      entity('line', 'Ligne', 'Lignes'),
      entity('equipment', 'Equipement', 'Equipements'),
      entity('machine', 'Machine', 'Machines'),
      entity('product-ref', 'Reference produit', 'References produit'),
      entity('workshop', 'Atelier', 'Ateliers'),
      entity('zone', 'Zone', 'Zones'),
    ],
    fields: [
      field('site', 'Site', 'entity', 'SITE', true),
      field('equipment', 'Equipement ou machine', 'entity', 'EQP'),
      field('line', 'Ligne ou atelier', 'free-text', 'LIGNE'),
      field('docType', 'Type de document', 'document-type', 'FT', true),
      field('reference', 'Reference', 'free-text', 'REF'),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoye', 'free-text'),
    ],
    documentTypes: [
      doc('technical-sheet', 'Fiche technique', 'FT', 'Technique', ['fiche produit']),
      doc('procedure', 'Procedure', 'PROC', 'Process', ['procedure']),
      doc('quality-report', 'Rapport qualite', 'RAP_QUAL', 'Qualite', ['rapport qualite']),
      doc('control', 'Controle', 'CTRL', 'Controle', ['controle']),
      doc('maintenance', 'Maintenance', 'MAINT', 'Maintenance', ['rapport maintenance']),
      doc('notice', 'Notice', 'NOTICE', 'Technique', ['manuel']),
      doc('intervention-plan', 'Plan d intervention', 'PI', 'Maintenance', ['plan intervention']),
      doc('non-conformity', 'Non-conformite', 'NC', 'Qualite', ['non conformite']),
      doc('equipment-sheet', 'Fiche equipement', 'FE', 'Equipement'),
      doc('test-report', 'Rapport de test', 'RAP_TEST', 'Qualite'),
      doc('certificate', 'Certificat', 'CERTIF', 'Qualite'),
      doc('prevention-plan', 'Plan de prevention', 'PP', 'Securite'),
      doc('operating-mode', 'Mode operatoire', 'MO', 'Process'),
      doc('checklist', 'Check-list', 'CHECK', 'Controle'),
      doc('incident-report', 'Rapport incident', 'RAP_INC', 'Securite'),
      doc('product-documentation', 'Documentation produit', 'DOC_PROD', 'Technique'),
    ],
    statuses: [...genericStatuses, doc('controlled', 'Controle', 'CONTROLE'), doc('non-compliant', 'Non conforme', 'NC')],
    templates: [
      template('industry-maintenance', 'Maintenance', 'Structure site, equipement, type, date et version.', ['site', 'equipment', 'docType', 'date', 'version'], 'SITE_EQP_MAINT_20260515_V01'),
      template('industry-quality', 'Qualite', 'Structure ligne, reference, type et statut.', ['line', 'reference', 'docType', 'status', 'version'], 'LIGNE_REF_RAP_QUAL_VALIDE_V01'),
      template('industry-equipment', 'Documentation equipement', 'Documentation rattachee a un equipement.', ['site', 'equipment', 'docType', 'reference', 'version'], 'SITE_EQP_FT_REF_V01'),
      template('industry-control', 'Controle', 'Controles, checklists et rapports.', ['site', 'line', 'docType', 'date', 'status'], 'SITE_LIGNE_CTRL_20260515_VALIDE'),
      template('custom', 'Convention personnalisee', 'Base libre a adapter.', ['site', 'docType', 'reference', 'version'], 'SITE_TYPE_REF_V01'),
    ],
  },
  {
    id: 'real-estate',
    label: 'Immobilier',
    shortLabel: 'Immobilier',
    description: 'Classement de baux, etats des lieux, diagnostics, quittances, dossiers bien et gestion locative.',
    recommendedFor: ['agences', 'gestionnaires locatifs', 'asset managers', 'syndics'],
    entityImportLabel: 'Importer des biens / locataires',
    defaultSeparator: '_',
    entityTypes: [
      entity('property', 'Bien', 'Biens'),
      entity('address', 'Adresse simplifiee', 'Adresses simplifiees'),
      entity('tenant', 'Locataire', 'Locataires'),
      entity('lessor', 'Bailleur', 'Bailleurs'),
      entity('agency', 'Agence', 'Agences'),
      entity('folder', 'Dossier', 'Dossiers'),
      entity('lot', 'Lot immobilier', 'Lots immobiliers'),
    ],
    fields: [
      field('property', 'Bien ou adresse', 'entity', 'BIEN', true),
      field('tenant', 'Locataire ou bailleur', 'entity', 'LOCATAIRE'),
      field('docType', 'Type de document', 'document-type', 'BAIL', true),
      field('reference', 'Reference', 'free-text', 'REF'),
      field('date', 'Date', 'date'),
      field('status', 'Statut', 'status', 'VALIDE'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoye', 'free-text'),
    ],
    documentTypes: [
      doc('lease', 'Bail', 'BAIL', 'Location', ['contrat de bail']),
      doc('inventory', 'Etat des lieux', 'EDL', 'Location', ['etat des lieux']),
      doc('mandate', 'Mandat', 'MANDAT', 'Gestion', ['mandat gestion']),
      doc('diagnostic', 'Diagnostic', 'DIAG', 'Technique', ['diagnostic immobilier']),
      doc('invoice', 'Facture', 'FAC', 'Comptabilite', ['invoice']),
      doc('receipt', 'Quittance', 'QUIT', 'Location', ['quittance loyer']),
      doc('tenant-mail', 'Courrier locataire', 'COUR_LOC', 'Courrier', ['courrier']),
      doc('property-file', 'Dossier bien', 'DOS_BIEN', 'Dossier', ['dossier immobilier']),
      doc('visit-minutes', 'Compte rendu visite', 'CR_VISITE', 'Commercial'),
      doc('insurance-certificate', 'Attestation assurance', 'ATT_ASSUR', 'Administratif'),
      doc('fund-call', 'Appel de fonds', 'ADF', 'Copropriete'),
      doc('ag-minutes', 'Proces-verbal AG', 'PV_AG', 'Copropriete'),
      doc('copro-rules', 'Reglement copropriete', 'REG_COPRO', 'Copropriete'),
      doc('plan', 'Plan', 'PLAN', 'Technique'),
      doc('photo', 'Photo', 'PHOTO', 'Media'),
      doc('works-quote', 'Devis travaux', 'DEVIS_TRAV', 'Travaux'),
      doc('technical-report', 'Rapport technique', 'RAP_TECH', 'Technique'),
    ],
    statuses: [...genericStatuses, doc('signed', 'Signe', 'SIGNE'), doc('pending', 'En attente', 'ATTENTE')],
    templates: [
      template('real-estate-property', 'Dossier bien', 'Structure bien, type, date et reference.', ['property', 'docType', 'date', 'reference', 'version'], 'BIEN_BAIL_20260515_REF_V01'),
      template('real-estate-rental', 'Gestion locative', 'Structure locataire, bien, type et date.', ['tenant', 'property', 'docType', 'date'], 'LOCATAIRE_BIEN_QUIT_20260515'),
      template('real-estate-copro', 'Copropriete', 'Structure bien et documents de copropriete.', ['property', 'docType', 'date', 'reference'], 'BIEN_PV_AG_20260515_REF'),
      template('real-estate-works', 'Travaux', 'Structure bien, travaux et reference.', ['property', 'docType', 'reference', 'version'], 'BIEN_DEVIS_TRAV_REF_V01'),
      template('custom', 'Convention personnalisee', 'Base libre a adapter.', ['property', 'docType', 'date', 'reference'], 'BIEN_TYPE_DATE_REF'),
    ],
  },
  {
    id: 'custom',
    label: 'Convention personnalisee',
    shortLabel: 'Custom',
    description: 'Profil generique pour composer vos propres champs, entites et conventions sans vocabulaire metier impose.',
    recommendedFor: ['equipes avec convention interne specifique'],
    entityImportLabel: 'Importer des entites',
    defaultSeparator: '_',
    entityTypes: [entity('entity', 'Entite', 'Entites')],
    fields: [
      field('entity', 'Entite', 'entity', 'ENTITE'),
      field('custom1', 'Champ 1', 'free-text', 'CHAMP1'),
      field('custom2', 'Champ 2', 'free-text', 'CHAMP2'),
      field('docType', 'Type de document', 'document-type', 'TYPE'),
      field('date', 'Date', 'date'),
      field('reference', 'Reference', 'free-text', 'REF'),
      field('status', 'Statut', 'status', 'STATUT'),
      field('version', 'Version', 'version', 'V01'),
      field('filename', 'Nom original nettoye', 'free-text'),
    ],
    documentTypes: [
      doc('document', 'Document', 'DOC'),
      doc('report', 'Rapport', 'RAP'),
      doc('note', 'Note', 'NOTE'),
      doc('record', 'Compte rendu', 'CR'),
      doc('form', 'Formulaire', 'FORM'),
    ],
    statuses: genericStatuses,
    templates: [
      template('custom-basic', 'Convention personnalisee', 'Base generique sans vocabulaire metier impose.', ['entity', 'docType', 'reference', 'version'], 'ENTITE_TYPE_REF_V01'),
    ],
  },
];
