/**
 * BIM Companies (Entreprises — fournisseurs & sous-traitants)
 * Ported 1:1 from extension/js/config.js — CONFIG.COMPANIES
 * Ordered alphabetically as in source.
 */

import type { Company } from '../types';

export const COMPANIES: Company[] = [
  { code: 'AGTAN', name: 'AGTAN', lots: [] },
  { code: 'DORMAKABA', name: 'DORMAKABA SCHWEIZ AG', lots: ['SER', 'MEN', 'CFA'] },
  { code: 'EBENISTERIE_MEYER_SUTER', name: 'EBENISTERIE MEYER ET SUTER SARL', lots: ['INT', 'MEN'] },
  { code: 'ECHAMI_LEMAN', name: 'ECHAMI LEMAN SA', lots: [] },
  { code: 'ECOSERVICES', name: 'ECOSERVICES SA', lots: ['ELE', 'VRD'] },
  { code: 'EIG_CRUSTAG', name: 'EIG CRUSTAG', lots: ['CFA', 'ELE'] },
  { code: 'ELECTROSUISSE', name: 'ELECTROSUISSE', lots: ['ELE'] },
  { code: 'EMMERICH', name: 'EMMERICH GmbH', lots: ['CVC'] },
  { code: 'ETAVIS', name: 'ETAVIS AG', lots: ['ELE', 'CFO', 'CFA'] },
  { code: 'EVOLE', name: 'EVOLE Sàrl', lots: [] },
  { code: 'FELLER', name: 'FELLER SA', lots: ['ELE', 'CFO'] },
  { code: 'FELLER_SCHNEIDER', name: 'FELLER BY SCHNEIDER ELECTRIC', lots: ['ELE', 'CFO'] },
  { code: 'FIRE_SYSTEM', name: 'FIRE SYSTEM SA', lots: ['SEC', 'SSI'] },
  { code: 'FIXIDE', name: 'FIXIDE POWER SYSTEMS SARL', lots: ['ELE', 'CFO'] },
  { code: 'GEBERIT', name: 'GEBERIT DISTRIBUTION SA', lots: ['SAN', 'PLB'] },
  { code: 'GK_RAUMCONCEPT', name: 'GK RAUMCONCEPT AG', lots: ['INT', 'FAC'] },
  { code: 'GROHE', name: 'GROHE GROUP SA', lots: ['SAN', 'PLB'] },
  { code: 'GRUNDFOS', name: 'GRUNDFOS HANDELS AG', lots: ['HYD', 'CHA', 'SAN'] },
  { code: 'GR_SANITAR', name: 'GR SANITÄR GmbH', lots: ['SAN', 'PLB'] },
  { code: 'HAKA_GERODUR', name: 'HAKA GERODUR AG', lots: ['SAN'] },
  { code: 'HANSGROHE', name: 'HANSGROHE AG', lots: ['SAN', 'PLB'] },
  { code: 'HEVRON', name: 'HEVRON SA', lots: ['CVC'] },
  { code: 'HOFMANN_PARATONNERRE', name: 'HOFMANN CAPT PARATONNERRE SARL', lots: ['ELE'] },
  { code: 'HW_ROMANDIE', name: 'HW ROMANDIE SA', lots: [] },
  { code: 'IFM', name: 'IFM', lots: ['GTB'] },
  { code: 'IMI_HYDRONIC', name: 'IMI HYDRONIC ENGINEERING SWITZERLAND AG', lots: ['HYD', 'CVC'] },
  { code: 'INDUNI', name: 'INDUNI & CIE SA, SUCCURSALE DE NYON', lots: ['STR', 'TER'] },
  { code: 'INEXIS', name: 'INEXIS Sàrl', lots: ['CFA', 'BIM'] },
  { code: 'JOSEPH_DIEMAND', name: 'JOSEPH DIEMAND SA', lots: [] },
  { code: 'KAESER', name: 'KAESER KOMPRESSOREN AG', lots: ['GAZ', 'CVC'] },
  { code: 'L_ATELIER_DU_PAYSAGE', name: "L'ATELIER DU PAYSAGE", lots: ['PAY'] },
  { code: 'LANZ_OENSINGEN', name: 'LANZ OENSINGEN AG', lots: ['VRD', 'CAN'] },
  { code: 'LEHMANN_GEOMETRE', name: 'LEHMANN GEOMETRE SA', lots: ['GEO'] },
  { code: 'LENZLINGER', name: 'LENZLINGER FILS SA', lots: ['TER', 'VRD'] },
  { code: 'MAZZOLI', name: 'MAZZOLI CREASTAFF SARL', lots: [] },
  { code: 'MDT_TECHNOLOGIES', name: 'MDT TECHNOLOGIES', lots: ['CFA', 'SEC'] },
  { code: 'MEIER_TOBLER', name: 'MEIER TOBLER', lots: ['CVC', 'CHA'] },
  { code: 'NEON_LUMIERES_STAUB', name: 'NEON LUMIERES STAUB SA', lots: ['LUM', 'ELE'] },
  { code: 'NEOVAC', name: 'NEOVAC AG', lots: ['CHA', 'SAN'] },
  { code: 'NET_POWERSAFE', name: 'NET POWERSAFE SA', lots: ['ELE', 'CFO'] },
  { code: 'NOVOFERM', name: 'NOVOFERM SCHWEIZ AG', lots: ['MEN', 'SER'] },
  { code: 'OLSY', name: 'OLSY SARL', lots: [] },
  { code: 'OPTIMALWAY', name: 'OPTIMALWAY SARL', lots: ['ELE', 'CFA'] },
  { code: 'PELLICHET_POSSE', name: 'PELLICHET POSSE SA', lots: ['FAC', 'COU'] },
  { code: 'PERFO_LUX', name: 'PERFO LUX SA', lots: ['LUM', 'ELE'] },
  { code: 'PERRIN_LANOIR', name: 'PERRIN ET LANOIR SA', lots: [] },
  { code: 'PHIDA_ETANCHEITE', name: 'PHIDA ETANCHEITE (GE) SA', lots: ['COU', 'FAC'] },
  { code: 'PLASTITECH', name: 'PLASTITECH SARL', lots: ['MEN', 'FAC'] },
  { code: 'POGAR', name: 'POGAR SA', lots: [] },
  { code: 'PRIMUS', name: 'PRIMUS AG', lots: ['CVC'] },
  { code: 'RATIONAL', name: 'RATIONAL', lots: ['CUI'] },
  { code: 'REGENT', name: 'REGENT SA', lots: ['LUM'] },
  { code: 'REICHEN_MASSARIE', name: 'REICHEN & P. DE MASSARIE AG – VERKAUF', lots: ['FAC', 'COU'] },
  { code: 'REMARQ_DENGES', name: 'REMARQ SA, SUCCURSALE DE DENGES', lots: [] },
  { code: 'ROMANDE_ENERGIE', name: 'ROMANDE ENERGIE SA', lots: ['ELE'] },
  { code: 'ROSCONI_SYSTEM', name: 'ROSCONI SYSTEM AG', lots: ['INT', 'MOB'] },
  { code: 'SAGERIME', name: 'SAGERIME SA', lots: ['GEO'] },
  { code: 'SAINT_GOBAIN', name: 'SAINT-GOBAIN', lots: ['FAC', 'INT'] },
  { code: 'SAMVAZ', name: 'SAMVAZ SA', lots: [] },
  { code: 'SCHNEIDER', name: 'SCHNEIDER ELECTRIC', lots: ['ELE', 'CFO', 'GTB'] },
  { code: 'SEECRET', name: 'SEECRET.CH', lots: ['SEC', 'CFA'] },
  { code: 'SIEMENS', name: 'SIEMENS', lots: ['ELE', 'CFO', 'GTB'] },
  { code: 'SIEMENS_SA', name: 'SIEMENS SA', lots: ['ELE', 'CFO', 'GTB'] },
  { code: 'SIKA', name: 'SIKA AG', lots: ['STR', 'FAC', 'COU'] },
  { code: 'SOLEOL', name: 'SOLEOL SA', lots: ['ELE'] },
  { code: 'START_CITY', name: 'START CITY SA', lots: [] },
  { code: 'STELO', name: 'STELO SA', lots: ['VRD'] },
  { code: 'STIVAC', name: 'STIVAC', lots: ['VEN', 'CVC'] },
  { code: 'STOCKLIN_LOGISTIK', name: 'STÖCKLIN LOGISTIK AG', lots: ['ASC', 'STR'] },
  { code: 'SUNGROW', name: 'SUNGROW DEUTSCHLAND GmbH', lots: ['ELE'] },
  { code: 'SURSECTOR', name: 'SURSECTOR SA', lots: ['SER', 'SEC'] },
  { code: 'SVS_SERRURERIE', name: 'SVS SERRURERIE DE VERSOIX SA', lots: ['SER'] },
  { code: 'SWEGON', name: 'SWEGON', lots: ['VEN', 'CVC'] },
  { code: 'TEMSA', name: 'TEMSA SA', lots: [] },
  { code: 'TOP_CABLE', name: 'TOP CABLE', lots: ['ELE', 'CFO'] },
  { code: 'TROX', name: 'TROX', lots: ['VEN', 'CVC'] },
  { code: 'UNIFIL', name: 'UNIFIL AG', lots: [] },
  { code: 'VERSUSS', name: 'VERSUSS Sàrl', lots: [] },
  { code: 'VOGEL', name: 'VOGEL SA', lots: ['HYD', 'CVC'] },
  { code: 'VUICHARD', name: 'VUICHARD GROUPE SA', lots: ['MEN', 'FAC'] },
  { code: 'WF_GMBH', name: 'WF GmbH', lots: [] },
  { code: 'WIELAND', name: 'WIELAND ELECTRIC AG', lots: ['ELE', 'CFO'] },
  { code: 'WILO', name: 'WILO', lots: ['HYD', 'CHA', 'SAN'] },
  { code: 'W_TISCH_REYMOND', name: 'W. TISCH-REYMOND SA', lots: [] },
];

export function getCompany(code: string): Company | undefined {
  return COMPANIES.find(c => c.code === code);
}

export function getCompaniesForLot(lotCode: string): Company[] {
  return COMPANIES.filter(c => c.lots.includes(lotCode));
}
