/**
 * BIM Companies (Entreprises — fournisseurs & sous-traitants)
 * Initial Swiss catalog extended with major French and Swiss AEC organizations.
 */

import type { Company } from '../types';

export const COMPANIES: Company[] = [
  { code: 'AGTAN', name: 'AGTAN', lots: [] },
  { code: 'DORMAKABA', name: 'DORMAKABA SCHWEIZ AG', lots: ['SER', 'MEN', 'CFA'] },
  { code: 'EBENISTERIE_MEYER_SUTER', name: 'EBENISTERIE MEYER ET SUTER SARL', lots: ['INT', 'MEN'] },
  { code: 'ECHAMI_LEMAN', name: 'ECHAMI LEMAN SA', lots: [] },
  { code: 'ECOSERVICES', name: 'ECOSERVICES SA', lots: ['ELE', 'VRD'] },
  { code: 'EIG_CRUSTAG', name: 'EIG CRUSTAG', lots: ['CFA', 'ELE'] },
  { code: 'ELECTROSUISSE', name: 'ELECTROSUISSE', lots: ['ELE'] },
  { code: 'EMMERICH', name: 'EMMERICH GmbH', lots: ['CVC'] },
  { code: 'ETAVIS', name: 'ETAVIS AG', lots: ['ELE', 'CFO', 'CFA'] },
  { code: 'EVOLE', name: 'EVOLE Sàrl', lots: [] },
  { code: 'FELLER', name: 'FELLER SA', lots: ['ELE', 'CFO'] },
  { code: 'FELLER_SCHNEIDER', name: 'FELLER BY SCHNEIDER ELECTRIC', lots: ['ELE', 'CFO'] },
  { code: 'FIRE_SYSTEM', name: 'FIRE SYSTEM SA', lots: ['SEC', 'SSI'] },
  { code: 'FIXIDE', name: 'FIXIDE POWER SYSTEMS SARL', lots: ['ELE', 'CFO'] },
  { code: 'GEBERIT', name: 'GEBERIT DISTRIBUTION SA', lots: ['SAN', 'PLB'] },
  { code: 'GK_RAUMCONCEPT', name: 'GK RAUMCONCEPT AG', lots: ['INT', 'FAC'] },
  { code: 'GROHE', name: 'GROHE GROUP SA', lots: ['SAN', 'PLB'] },
  { code: 'GRUNDFOS', name: 'GRUNDFOS HANDELS AG', lots: ['HYD', 'CHA', 'SAN'] },
  { code: 'GR_SANITAR', name: 'GR SANITÄR GmbH', lots: ['SAN', 'PLB'] },
  { code: 'HAKA_GERODUR', name: 'HAKA GERODUR AG', lots: ['SAN'] },
  { code: 'HANSGROHE', name: 'HANSGROHE AG', lots: ['SAN', 'PLB'] },
  { code: 'HEVRON', name: 'HEVRON SA', lots: ['CVC'] },
  { code: 'HOFMANN_PARATONNERRE', name: 'HOFMANN CAPT PARATONNERRE SARL', lots: ['ELE'] },
  { code: 'HW_ROMANDIE', name: 'HW ROMANDIE SA', lots: [] },
  { code: 'IFM', name: 'IFM', lots: ['GTB'] },
  { code: 'IMI_HYDRONIC', name: 'IMI HYDRONIC ENGINEERING SWITZERLAND AG', lots: ['HYD', 'CVC'] },
  { code: 'INDUNI', name: 'INDUNI & CIE SA, SUCCURSALE DE NYON', lots: ['STR', 'TER'] },
  { code: 'INEXIS', name: 'INEXIS Sàrl', lots: ['CFA', 'BIM'] },
  { code: 'JOSEPH_DIEMAND', name: 'JOSEPH DIEMAND SA', lots: [] },
  { code: 'KAESER', name: 'KAESER KOMPRESSOREN AG', lots: ['GAZ', 'CVC'] },
  { code: 'L_ATELIER_DU_PAYSAGE', name: "L'ATELIER DU PAYSAGE", lots: ['PAY'] },
  { code: 'LANZ_OENSINGEN', name: 'LANZ OENSINGEN AG', lots: ['VRD', 'CAN'] },
  { code: 'LEHMANN_GEOMETRE', name: 'LEHMANN GEOMETRE SA', lots: ['GEO'] },
  { code: 'LENZLINGER', name: 'LENZLINGER FILS SA', lots: ['TER', 'VRD'] },
  { code: 'MAZZOLI', name: 'MAZZOLI CREASTAFF SARL', lots: [] },
  { code: 'MDT_TECHNOLOGIES', name: 'MDT TECHNOLOGIES', lots: ['CFA', 'SEC'] },
  { code: 'MEIER_TOBLER', name: 'MEIER TOBLER', lots: ['CVC', 'CHA'] },
  { code: 'NEON_LUMIERES_STAUB', name: 'NEON LUMIERES STAUB SA', lots: ['LUM', 'ELE'] },
  { code: 'NEOVAC', name: 'NEOVAC AG', lots: ['CHA', 'SAN'] },
  { code: 'NET_POWERSAFE', name: 'NET POWERSAFE SA', lots: ['ELE', 'CFO'] },
  { code: 'NOVOFERM', name: 'NOVOFERM SCHWEIZ AG', lots: ['MEN', 'SER'] },
  { code: 'OLSY', name: 'OLSY SARL', lots: [] },
  { code: 'OPTIMALWAY', name: 'OPTIMALWAY SARL', lots: ['ELE', 'CFA'] },
  { code: 'PELLICHET_POSSE', name: 'PELLICHET POSSE SA', lots: ['FAC', 'COU'] },
  { code: 'PERFO_LUX', name: 'PERFO LUX SA', lots: ['LUM', 'ELE'] },
  { code: 'PERRIN_LANOIR', name: 'PERRIN ET LANOIR SA', lots: [] },
  { code: 'PHIDA_ETANCHEITE', name: 'PHIDA ETANCHEITE (GE) SA', lots: ['COU', 'FAC'] },
  { code: 'PLASTITECH', name: 'PLASTITECH SARL', lots: ['MEN', 'FAC'] },
  { code: 'POGAR', name: 'POGAR SA', lots: [] },
  { code: 'PRIMUS', name: 'PRIMUS AG', lots: ['CVC'] },
  { code: 'RATIONAL', name: 'RATIONAL', lots: ['CUI'] },
  { code: 'REGENT', name: 'REGENT SA', lots: ['LUM'] },
  { code: 'REICHEN_MASSARIE', name: 'REICHEN & P. DE MASSARIE AG – VERKAUF', lots: ['FAC', 'COU'] },
  { code: 'REMARQ_DENGES', name: 'REMARQ SA, SUCCURSALE DE DENGES', lots: [] },
  { code: 'ROMANDE_ENERGIE', name: 'ROMANDE ENERGIE SA', lots: ['ELE'] },
  { code: 'ROSCONI_SYSTEM', name: 'ROSCONI SYSTEM AG', lots: ['INT', 'MOB'] },
  { code: 'SAGERIME', name: 'SAGERIME SA', lots: ['GEO'] },
  { code: 'SAINT_GOBAIN', name: 'SAINT-GOBAIN', lots: ['FAC', 'INT'] },
  { code: 'SAMVAZ', name: 'SAMVAZ SA', lots: [] },
  { code: 'SCHNEIDER', name: 'SCHNEIDER ELECTRIC', lots: ['ELE', 'CFO', 'GTB'] },
  { code: 'SEECRET', name: 'SEECRET.CH', lots: ['SEC', 'CFA'] },
  { code: 'SIEMENS', name: 'SIEMENS', lots: ['ELE', 'CFO', 'GTB'] },
  { code: 'SIEMENS_SA', name: 'SIEMENS SA', lots: ['ELE', 'CFO', 'GTB'] },
  { code: 'SIKA', name: 'SIKA AG', lots: ['STR', 'FAC', 'COU'] },
  { code: 'SOLEOL', name: 'SOLEOL SA', lots: ['ELE'] },
  { code: 'START_CITY', name: 'START CITY SA', lots: [] },
  { code: 'STELO', name: 'STELO SA', lots: ['VRD'] },
  { code: 'STIVAC', name: 'STIVAC', lots: ['VEN', 'CVC'] },
  { code: 'STOCKLIN_LOGISTIK', name: 'STÖCKLIN LOGISTIK AG', lots: ['ASC', 'STR'] },
  { code: 'SUNGROW', name: 'SUNGROW DEUTSCHLAND GmbH', lots: ['ELE'] },
  { code: 'SURSECTOR', name: 'SURSECTOR SA', lots: ['SER', 'SEC'] },
  { code: 'SVS_SERRURERIE', name: 'SVS SERRURERIE DE VERSOIX SA', lots: ['SER'] },
  { code: 'SWEGON', name: 'SWEGON', lots: ['VEN', 'CVC'] },
  { code: 'TEMSA', name: 'TEMSA SA', lots: [] },
  { code: 'TOP_CABLE', name: 'TOP CABLE', lots: ['ELE', 'CFO'] },
  { code: 'TROX', name: 'TROX', lots: ['VEN', 'CVC'] },
  { code: 'UNIFIL', name: 'UNIFIL AG', lots: [] },
  { code: 'VERSUSS', name: 'VERSUSS Sàrl', lots: [] },
  { code: 'VOGEL', name: 'VOGEL SA', lots: ['HYD', 'CVC'] },
  { code: 'VUICHARD', name: 'VUICHARD GROUPE SA', lots: ['MEN', 'FAC'] },
  { code: 'WF_GMBH', name: 'WF GmbH', lots: [] },
  { code: 'WIELAND', name: 'WIELAND ELECTRIC AG', lots: ['ELE', 'CFO'] },
  { code: 'WILO', name: 'WILO', lots: ['HYD', 'CHA', 'SAN'] },
  { code: 'W_TISCH_REYMOND', name: 'W. TISCH-REYMOND SA', lots: [] },

  // France — architecture, ingénierie, construction, réseaux et équipements
  { code: 'ACOUPHEN', name: 'ACOUPHEN', lots: ['SYN', 'BIM'] },
  { code: 'AIA_LIFE_DESIGNERS', name: 'AIA LIFE DESIGNERS', lots: ['ARC', 'BIM', 'SYN'] },
  { code: 'ALTAREA', name: 'ALTAREA', lots: ['ARC', 'BIM', 'SYN'] },
  { code: 'APAVE', name: 'APAVE', lots: ['SYN', 'BIM', 'STR', 'SEC'] },
  { code: 'AREP', name: 'AREP', lots: ['ARC', 'BIM', 'SYN'] },
  { code: 'ARTELIA', name: 'ARTELIA', lots: ['BIM', 'SYN', 'CVC', 'ELE', 'STR', 'VRD'] },
  { code: 'ASSYSTEM', name: 'ASSYSTEM', lots: ['BIM', 'SYN', 'ELE', 'CVC'] },
  { code: 'ATELIERS_JEAN_NOUVEL', name: 'ATELIERS JEAN NOUVEL', lots: ['ARC', 'BIM'] },
  { code: 'AXIMA_CONCEPT', name: 'AXIMA CONCEPT', lots: ['CVC', 'VEN', 'CLI', 'GTB'] },
  { code: 'BAUDIN_CHATEAUNEUF', name: 'BAUDIN CHATEAUNEUF', lots: ['STR', 'SER'] },
  { code: 'BOUYGUES_BATIMENT', name: 'BOUYGUES BÂTIMENT', lots: ['STR', 'ARC', 'FAC', 'BIM', 'SYN'] },
  { code: 'BOUYGUES_ENERGIES_SERVICES', name: 'BOUYGUES ENERGIES & SERVICES', lots: ['ELE', 'CFO', 'CFA', 'CVC', 'GTB'] },
  { code: 'BTP_CONSULTANTS', name: 'BTP CONSULTANTS', lots: ['SYN', 'BIM', 'STR', 'SEC'] },
  { code: 'BUREAU_VERITAS_CONSTRUCTION', name: 'BUREAU VERITAS CONSTRUCTION', lots: ['SYN', 'BIM', 'STR', 'SEC'] },
  { code: 'CARDONNEL_INGENIERIE', name: 'CARDONNEL INGÉNIERIE', lots: ['CVC', 'CHA', 'ELE', 'GTB'] },
  { code: 'CEGELEC', name: 'CEGELEC', lots: ['ELE', 'CFO', 'CFA', 'GTB'] },
  { code: 'CHARIER', name: 'CHARIER', lots: ['VRD', 'TER', 'CAN'] },
  { code: 'COLAS', name: 'COLAS', lots: ['VRD', 'TER', 'CAN'] },
  { code: 'DALKIA', name: 'DALKIA', lots: ['CVC', 'CHA', 'GTB'] },
  { code: 'DEKRA_INDUSTRIAL', name: 'DEKRA INDUSTRIAL', lots: ['SYN', 'STR', 'SEC'] },
  { code: 'DEMATHIEU_BARD', name: 'DEMATHIEU BARD', lots: ['STR', 'ARC', 'VRD'] },
  { code: 'EDEIS', name: 'EDEIS', lots: ['BIM', 'SYN', 'STR', 'CVC', 'ELE'] },
  { code: 'EGIS', name: 'EGIS', lots: ['BIM', 'SYN', 'STR', 'VRD', 'CVC', 'ELE'] },
  { code: 'EIFFAGE_CONSTRUCTION', name: 'EIFFAGE CONSTRUCTION', lots: ['STR', 'ARC', 'FAC', 'BIM'] },
  { code: 'EIFFAGE_ENERGIE_SYSTEMES', name: 'EIFFAGE ÉNERGIE SYSTÈMES', lots: ['ELE', 'CFO', 'CFA', 'CVC', 'GTB'] },
  { code: 'ENGIE_SOLUTIONS', name: 'ENGIE SOLUTIONS', lots: ['CVC', 'CHA', 'ELE', 'GTB'] },
  { code: 'EQUANS_FRANCE', name: 'EQUANS FRANCE', lots: ['ELE', 'CFO', 'CFA', 'CVC', 'GTB'] },
  { code: 'EUROVIA', name: 'EUROVIA', lots: ['VRD', 'TER', 'CAN'] },
  { code: 'FAYAT_BATIMENT', name: 'FAYAT BÂTIMENT', lots: ['STR', 'ARC', 'FAC'] },
  { code: 'FAYAT_ENERGIE_SERVICES', name: 'FAYAT ÉNERGIE SERVICES', lots: ['ELE', 'CFO', 'CFA', 'CVC', 'GTB'] },
  { code: 'FREYSSINET', name: 'FREYSSINET', lots: ['STR', 'FOU'] },
  { code: 'GCC_CONSTRUCTION', name: 'GCC CONSTRUCTION', lots: ['STR', 'ARC', 'FAC'] },
  { code: 'GINGER_BURGEAP', name: 'GINGER BURGEAP', lots: ['GEO', 'TER', 'VRD'] },
  { code: 'GROUPE_6', name: 'GROUPE-6', lots: ['ARC', 'BIM', 'SYN'] },
  { code: 'HERVE_THERMIQUE', name: 'HERVÉ THERMIQUE', lots: ['CVC', 'CHA', 'VEN', 'ELE', 'GTB'] },
  { code: 'IDOM_FRANCE', name: 'IDOM FRANCE', lots: ['BIM', 'SYN', 'STR', 'CVC', 'ELE'] },
  { code: 'INGEROP', name: 'INGEROP', lots: ['BIM', 'SYN', 'STR', 'VRD', 'CVC', 'ELE'] },
  { code: 'KAUFMAN_BROAD', name: 'KAUFMAN & BROAD', lots: ['ARC', 'BIM', 'SYN'] },
  { code: 'KONE_FRANCE', name: 'KONE FRANCE', lots: ['ASC'] },
  { code: 'LEON_GROSSE', name: 'LÉON GROSSE', lots: ['STR', 'ARC', 'FAC'] },
  { code: 'LEGENDRE_CONSTRUCTION', name: 'LEGENDRE CONSTRUCTION', lots: ['STR', 'ARC', 'FAC'] },
  { code: 'NGE', name: 'NGE', lots: ['VRD', 'TER', 'CAN', 'STR'] },
  { code: 'NEXITY', name: 'NEXITY', lots: ['ARC', 'BIM', 'SYN'] },
  { code: 'OTIS_FRANCE', name: 'OTIS FRANCE', lots: ['ASC'] },
  { code: 'QUALICONSULT', name: 'QUALICONSULT', lots: ['SYN', 'BIM', 'STR', 'SEC'] },
  { code: 'RAZEL_BEC', name: 'RAZEL-BEC', lots: ['VRD', 'TER', 'STR'] },
  { code: 'SADE', name: 'SADE', lots: ['CAN', 'VRD', 'HYD'] },
  { code: 'SETEC', name: 'SETEC', lots: ['BIM', 'SYN', 'STR', 'VRD', 'CVC', 'ELE'] },
  { code: 'SNEF', name: 'SNEF', lots: ['ELE', 'CFO', 'CFA', 'GTB'] },
  { code: 'SOCOTEC', name: 'SOCOTEC', lots: ['SYN', 'BIM', 'STR', 'SEC'] },
  { code: 'SPIE_BATIGNOLLES', name: 'SPIE BATIGNOLLES', lots: ['STR', 'ARC', 'VRD', 'TER'] },
  { code: 'SPIE_FRANCE', name: 'SPIE FRANCE', lots: ['ELE', 'CFO', 'CFA', 'CVC', 'GTB'] },
  { code: 'SUEZ', name: 'SUEZ', lots: ['HYD', 'CAN', 'GTB'] },
  { code: 'SYSTRA', name: 'SYSTRA', lots: ['BIM', 'SYN', 'STR', 'VRD'] },
  { code: 'VEOLIA', name: 'VEOLIA', lots: ['HYD', 'CAN', 'GTB'] },
  { code: 'VINCI_CONSTRUCTION', name: 'VINCI CONSTRUCTION', lots: ['STR', 'ARC', 'FAC', 'BIM', 'SYN'] },
  { code: 'VINCI_ENERGIES', name: 'VINCI ENERGIES', lots: ['ELE', 'CFO', 'CFA', 'CVC', 'GTB'] },
  { code: 'WSP_FRANCE', name: 'WSP FRANCE', lots: ['BIM', 'SYN', 'STR', 'CVC', 'ELE'] },

  // Suisse — architecture, ingénierie, construction, réseaux et équipements
  { code: 'ABB_SUISSE', name: 'ABB SUISSE', lots: ['ELE', 'CFO', 'GTB'] },
  { code: 'AFRY_SUISSE', name: 'AFRY SUISSE', lots: ['BIM', 'SYN', 'STR', 'CVC', 'ELE'] },
  { code: 'ALPIQ', name: 'ALPIQ', lots: ['ELE', 'CFO', 'CVC', 'GTB'] },
  { code: 'AMSTEIN_WALTHERT', name: 'AMSTEIN + WALTHERT', lots: ['CVC', 'ELE', 'CFO', 'CFA', 'GTB', 'BIM'] },
  { code: 'ARUP_SUISSE', name: 'ARUP SUISSE', lots: ['BIM', 'SYN', 'STR', 'CVC', 'ELE'] },
  { code: 'BASLER_HOFMANN', name: 'BASLER & HOFMANN', lots: ['BIM', 'SYN', 'STR', 'VRD', 'CVC'] },
  { code: 'BELIMO', name: 'BELIMO', lots: ['CVC', 'VEN', 'GTB'] },
  { code: 'BG_INGENIEURS_CONSEILS', name: 'BG INGÉNIEURS CONSEILS', lots: ['BIM', 'SYN', 'STR', 'VRD', 'CVC'] },
  { code: 'BKW_BUILDING_SOLUTIONS', name: 'BKW BUILDING SOLUTIONS', lots: ['ELE', 'CFO', 'CFA', 'CVC', 'GTB'] },
  { code: 'BOBST_ARCHITECTES', name: 'BOBST ARCHITECTES', lots: ['ARC', 'BIM'] },
  { code: 'BOUYGUES_ENERGIES_SERVICES_CH', name: 'BOUYGUES ENERGIES & SERVICES SUISSE', lots: ['ELE', 'CFO', 'CFA', 'CVC', 'GTB'] },
  { code: 'BURCKHARDT_PARTNER', name: 'BURCKHARDT + PARTNER', lots: ['ARC', 'BIM', 'SYN'] },
  { code: 'BURKHALTER_TECHNICS', name: 'BURKHALTER TECHNICS', lots: ['ELE', 'CFO', 'CFA', 'GTB'] },
  { code: 'CCHE', name: 'CCHE', lots: ['ARC', 'BIM'] },
  { code: 'CSD_INGENIEURS', name: 'CSD INGÉNIEURS', lots: ['BIM', 'SYN', 'STR', 'VRD', 'GEO'] },
  { code: 'EBP_SCHWEIZ', name: 'EBP SCHWEIZ', lots: ['BIM', 'SYN', 'STR', 'VRD'] },
  { code: 'EMCH_BERGER', name: 'EMCH+BERGER', lots: ['BIM', 'SYN', 'STR', 'VRD', 'CVC'] },
  { code: 'ENERGIE_360', name: 'ENERGIE 360°', lots: ['CHA', 'HYD', 'GTB'] },
  { code: 'EQUANS_SWITZERLAND', name: 'EQUANS SWITZERLAND', lots: ['ELE', 'CFO', 'CFA', 'CVC', 'GTB'] },
  { code: 'ERNE', name: 'ERNE', lots: ['STR', 'ARC', 'FAC', 'BIM'] },
  { code: 'FERRARI_ARCHITECTES', name: 'FERRARI ARCHITECTES', lots: ['ARC', 'BIM'] },
  { code: 'GEX_DORTHE', name: 'GEX & DORTHE', lots: ['ARC', 'BIM'] },
  { code: 'GRUNER', name: 'GRUNER', lots: ['BIM', 'SYN', 'STR', 'CVC', 'ELE'] },
  { code: 'HAGER_SUISSE', name: 'HAGER SUISSE', lots: ['ELE', 'CFO'] },
  { code: 'HALTER', name: 'HALTER', lots: ['ARC', 'STR', 'BIM', 'SYN'] },
  { code: 'HELBLING', name: 'HELBLING', lots: ['BIM', 'SYN', 'CVC', 'ELE'] },
  { code: 'HILTI_SUISSE', name: 'HILTI SUISSE', lots: ['STR', 'FAC', 'CVC', 'ELE'] },
  { code: 'HOLCIM_SUISSE', name: 'HOLCIM SUISSE', lots: ['STR', 'FAC'] },
  { code: 'HRS_REAL_ESTATE', name: 'HRS REAL ESTATE', lots: ['ARC', 'STR', 'BIM', 'SYN'] },
  { code: 'IMPLENIA', name: 'IMPLENIA', lots: ['STR', 'ARC', 'VRD', 'BIM', 'SYN'] },
  { code: 'JPF_CONSTRUCTION', name: 'JPF CONSTRUCTION', lots: ['STR', 'ARC', 'FAC'] },
  { code: 'KIBAG', name: 'KIBAG', lots: ['STR', 'TER', 'VRD'] },
  { code: 'KONE_SUISSE', name: 'KONE SUISSE', lots: ['ASC'] },
  { code: 'LEGRAND_SUISSE', name: 'LEGRAND SUISSE', lots: ['ELE', 'CFO', 'CFA'] },
  { code: 'LOSINGER_MARAZZI', name: 'LOSINGER MARAZZI', lots: ['STR', 'ARC', 'BIM', 'SYN'] },
  { code: 'MARTI', name: 'MARTI', lots: ['STR', 'TER', 'VRD'] },
  { code: 'MONOD_PIGUET', name: 'MONOD-PIGUET + ASSOCIÉS', lots: ['STR', 'SYN', 'BIM'] },
  { code: 'ORLLATI', name: 'ORLLATI', lots: ['TER', 'DEM', 'VRD', 'STR'] },
  { code: 'OTIS_SUISSE', name: 'OTIS SUISSE', lots: ['ASC'] },
  { code: 'PENSIMO', name: 'PENSIMO', lots: ['ARC', 'BIM', 'SYN'] },
  { code: 'PLANAR', name: 'PLANAR', lots: ['BIM', 'SYN', 'CVC', 'ELE'] },
  { code: 'POM_PLUS', name: 'POM+', lots: ['BIM', 'SYN', 'GTB'] },
  { code: 'PROGIN', name: 'PROGIN', lots: ['BIM', 'SYN', 'STR', 'CVC', 'ELE'] },
  { code: 'RAPP', name: 'RAPP', lots: ['BIM', 'SYN', 'STR', 'VRD', 'CVC'] },
  { code: 'RDR_ARCHITECTES', name: 'RDR ARCHITECTES', lots: ['ARC', 'BIM'] },
  { code: 'SABAG', name: 'SABAG', lots: ['SAN', 'PLB', 'CUI'] },
  { code: 'SANITAS_TROESCH', name: 'SANITAS TROESCH', lots: ['SAN', 'PLB', 'CUI'] },
  { code: 'SBB_CFF_FFS', name: 'SBB CFF FFS', lots: ['BIM', 'SYN', 'VRD', 'ELE'] },
  { code: 'SCHERLER', name: 'SCHERLER', lots: ['ELE', 'CFO', 'CFA', 'GTB'] },
  { code: 'SCHINDLER_SUISSE', name: 'SCHINDLER SUISSE', lots: ['ASC'] },
  { code: 'SCRASA', name: 'SCRASA', lots: ['VRD', 'TER', 'CAN'] },
  { code: 'SERVICES_INDUSTRIELS_LAUSANNE', name: 'SERVICES INDUSTRIELS DE LAUSANNE', lots: ['ELE', 'HYD', 'CAN'] },
  { code: 'SIG', name: 'SERVICES INDUSTRIELS DE GENÈVE', lots: ['ELE', 'HYD', 'CAN'] },
  { code: 'STEINER', name: 'STEINER', lots: ['STR', 'ARC', 'BIM', 'SYN'] },
  { code: 'TEKHNE', name: 'TEKHNÉ', lots: ['ARC', 'BIM', 'SYN'] },
  { code: 'V_ZUG', name: 'V-ZUG', lots: ['CUI', 'ELE'] },
  { code: 'VELUX_SUISSE', name: 'VELUX SUISSE', lots: ['COU', 'MEN', 'FAC'] },
  { code: 'WSP_SUISSE', name: 'WSP SUISSE', lots: ['BIM', 'SYN', 'STR', 'CVC', 'ELE'] },
  { code: 'ZPF_INGENIEURE', name: 'ZPF INGENIEURE', lots: ['BIM', 'SYN', 'STR'] },
];

export function getCompany(code: string): Company | undefined {
  return COMPANIES.find(c => c.code === code);
}

export function getCompaniesForLot(lotCode: string): Company[] {
  return COMPANIES.filter(c => c.lots.includes(lotCode));
}
